#!/bin/sh
# Generated by Assura agent integration lifecycle
set -eu

PROJECT_ROOT="${ASSURA_PROJECT_ROOT:-.}"
MODE="${ASSURA_AGENT_MODE:-nudge}"
EVENT="${ASSURA_AGENT_EVENT:-session-start}"
ASSURA_AGENT_LOG="${ASSURA_AGENT_LOG:-1}"
ASSURA_AGENT_LOG_DIR="${ASSURA_AGENT_LOG_DIR:-$PROJECT_ROOT/.assura/agent-sessions}"
if [ -z "${ASSURA_AGENT_SESSION_ID:-}" ]; then
  ASSURA_AGENT_SESSION_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
fi
export ASSURA_AGENT_LOG ASSURA_AGENT_LOG_DIR ASSURA_AGENT_SESSION_ID

run_assura() {
  if [ -n "${ASSURA_BIN:-}" ] && [ -x "$ASSURA_BIN" ]; then
    "$ASSURA_BIN" "$@"
  elif command -v assura >/dev/null 2>&1; then
    assura "$@"
  elif [ -x "$PROJECT_ROOT/target/debug/assura" ]; then
    "$PROJECT_ROOT/target/debug/assura" "$@"
  elif command -v cargo >/dev/null 2>&1; then
    (cd "$PROJECT_ROOT" && cargo run --quiet -- "$@")
  else
    echo "assura command not found and local cargo fallback is unavailable" >&2
    return 127
  fi
}

case "$MODE" in
  nudge)
    run_assura agent nudge "$PROJECT_ROOT" --agent codex --event "$EVENT" --format json "$@"
    ;;
  check)
    run_assura check "$PROJECT_ROOT" --format agent --agent codex --warn "$@"
    ;;
  daemon-status)
    run_assura daemon status "$PROJECT_ROOT" --format json "$@"
    ;;
  daemon-doctor)
    run_assura daemon doctor "$PROJECT_ROOT" --format json "$@"
    ;;
  *)
    echo "Unsupported ASSURA_AGENT_MODE: $MODE" >&2
    exit 2
    ;;
esac
