//! Evidence-first handoff files generated by `assura agent onboard`.

pub(super) fn questions() -> &'static str {
    r#"# Assura Onboarding Questions

Answer these from repository evidence when the intent is clear. Ask the project
owner only where manifests, tooling, documentation, and established structure
do not provide a reliable answer.

1. What primary language or stack should this project use?
2. What project type is this: library, app, docs site, research-authoring project, data project, monorepo, or other?
3. What file naming convention should apply: kebab-case, snake_case, PascalCase, or mixed by folder?
4. What source layout should the project use?
5. What test layout should the project use?
6. Should docs be strict from day one or advisory until the first milestone?
7. Should agent hooks be advisory only while working and blocking only in CI?
8. Are there required files or folders specific to this project?
9. Are there binary or source documents that should be tracked by manifest instead of read as text?
10. Should Assura create typed content models for tasks, decisions, requirements, evidence, or source documents?
"#
}

pub(super) fn lifecycle() -> &'static str {
    r#"# Assura Lifecycle Profiles

Use these modes consistently:

| Mode | When | Blocking | Command |
| --- | --- | --- | --- |
| nudge | During agent working loops, path-aware tool events, and idle reviews | no | `assura agent nudge --event before-tool --changed <path> --format json .` |
| warn | Before local commits or while drafting | no | `assura check --format agent --warn --min-severity low --max-issues 10 .` |
| gate | Before push, merge, or CI | yes | `assura check --format agent --min-severity medium --max-issues 20 .` |

Host-agent integrations are reviewable local bundles under
`.assura/integrations/<agent>/`. Installation does not change host settings.
Run `assura agent integration activate <agent> .` to patch only Assura-owned
project host configuration, then `assura agent integration doctor <agent> .`
to verify the managed files. Host trust remains under user control.
"#
}

pub(super) fn agent_next() -> &'static str {
    r#"# Agent Next

Assura is installed. Read `.assura/onboarding/rules.md` to confirm whether the
recommended baseline is applied, available, not applied, or needs conflict
resolution.

Read `.assura/onboarding/rules.md` before editing the project-owned recipe
rules in `.assura/config.yml`.

## Inspect Project Evidence First

1. Inspect package and workspace manifests, framework configuration, build and
   test tooling, generated-output settings, project docs, and established paths.
2. Infer the expected stack and intentional layout from converging evidence.
   Do not assume every observed file or directory is intentional.
3. Define project-owned rules in `.assura/config.yml` for expected root files,
   source and test areas, workspace packages, naming, and generated output.
4. Close stable scopes so unexpected files and directories fail. Preserve
   legitimate existing paths and keep uncertain or actively evolving scopes
   open until their intent is confirmed.
5. Ask only where the evidence is ambiguous or a choice would reject existing
   project content.

Use `.assura/onboarding/lifecycle.md` to decide between nudge, warn, and gate
feedback. Warn mode is advisory for draft work; gate mode is for pre-push,
merge, or CI checks.

For structure mismatches, apply `STRUCTURE_FIT_CHECK` from
`.agents/skills/assura-structure-fit/references/structure-fit-check.md` before
editing `.assura/config.yml`.

## Resolve Remaining Questions

1. What primary language or stack should this project use?
2. What project type is this: library, app, docs site, research-authoring project, data project, monorepo, or other?
3. What file naming convention should apply: kebab-case, snake_case, PascalCase, or mixed by folder?
4. What source layout should the project use?
5. What test layout should the project use?
6. Should docs be strict from day one or advisory until the first milestone?
7. Should agent hooks be advisory only while working and blocking only in CI?
8. Are there required files or folders specific to this project?
9. Are there binary or source documents that should be tracked by manifest instead of read as text?
10. Should Assura create typed content models for tasks, decisions, requirements, evidence, or source documents?

## After The User Answers

Record answers in `.assura/onboarding/answers.yml` or equivalent project notes,
update the project-owned rules, then run `assura review` followed by
`assura check --format agent .`. Summarize active checks, open scopes, and any
remaining decisions.
"#
}
