//! Document-project files generated by `assura agent onboard`.

use crate::cli::agent_onboarding_content_templates::{
    agent_project_content_collections, agent_project_content_relations, content_model_header,
};
use crate::cli::agent_onboarding_templates::GeneratedFile;

pub(super) fn content_config() -> String {
    format!(
        "{}{}{}{}{}",
        content_model_header(),
        agent_project_content_collections(),
        DOCUMENT_PROJECT_COLLECTIONS,
        agent_project_content_relations(),
        DOCUMENT_PROJECT_RELATIONS
    )
}

pub(super) fn root_required_dirs() -> &'static str {
    r#"        - "library"
        - "source-documents"
"#
}

pub(super) fn root_structure() -> &'static str {
    r#"  library/:
    required: true
    topics/: exists:1
  library/topics/:
    required: true
    topic-document-project-baseline.md: exists:1
  source-documents/:
    required: true
    manifest.md: exists:1
    files/: exists:1
"#
}

pub(super) fn docs_structure() -> &'static str {
    r#"    requirements/: exists:1
    evidence/: exists:1
    decisions/: exists:1
    drafts/: exists:1
    final/: exists:1
"#
}

pub(super) fn files() -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::static_file(
            "library/topics/topic-document-project-baseline.md",
            topic_document_project_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/drafts/draft-document-project-baseline.md",
            draft_document_project_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/final/final-document-project-baseline.md",
            final_document_project_baseline(),
        ),
        GeneratedFile::static_file("source-documents/manifest.md", source_documents_manifest()),
        GeneratedFile::static_file(
            "source-documents/files/sample-source.txt",
            source_document_sample_file(),
        ),
    ]
}

const DOCUMENT_PROJECT_COLLECTIONS: &str = r#"  topics:
    class: Topic
    path: "library/topics/*.md"
    adapter: markdown_frontmatter
    id: id
  drafts:
    class: Draft
    path: "docs/drafts/*.md"
    adapter: markdown_frontmatter
    id: id
  final_docs:
    class: FinalDocument
    path: "docs/final/*.md"
    adapter: markdown_frontmatter
    id: id
  source_documents:
    class: SourceDocument
    path: "source-documents/manifest.md"
    adapter: markdown_frontmatter
    id: id
"#;

const DOCUMENT_PROJECT_RELATIONS: &str = r#"  topics.related_requirements:
    target: requirements
    many: true
  drafts.requirements:
    target: requirements
    many: true
  drafts.evidence:
    target: evidence
    many: true
  final_docs.requirements:
    target: requirements
    many: true
  final_docs.evidence:
    target: evidence
    many: true
  source_documents.related_requirements:
    target: requirements
    many: true
"#;

fn topic_document_project_baseline() -> &'static str {
    r#"---
id: topic-document-project-baseline
title: Document Project Baseline Topic
status: active
related_requirements:
  - requirement-agent-content-baseline
summary: A starter topic that demonstrates the document-project library shape.
---

# Document Project Baseline Topic

Use topics for reusable research, domain notes, or knowledge-base material that
should inform drafts and final documents.
"#
}

fn draft_document_project_baseline() -> &'static str {
    r#"---
id: draft-document-project-baseline
title: Document Project Baseline Draft
status: draft
requirements:
  - requirement-agent-content-baseline
evidence:
  - evidence-agent-content-baseline
summary: A starter draft linked to generic requirements and evidence.
---

# Document Project Baseline Draft

Use drafts for work in progress that still needs review, evidence checks, or
source-document reconciliation before it becomes final.
"#
}

fn final_document_project_baseline() -> &'static str {
    r#"---
id: final-document-project-baseline
title: Document Project Baseline Final Document
status: final
requirements:
  - requirement-agent-content-baseline
evidence:
  - evidence-agent-content-baseline
summary: A starter final document linked to generic requirements and evidence.
---

# Document Project Baseline Final Document

Use final documents for reviewed outputs that should remain traceable to
requirements, evidence, and source-document custody metadata.
"#
}

fn source_documents_manifest() -> &'static str {
    r#"---
id: source-documents-manifest
title: Source Documents Manifest
status: available
kind: local-fixture
origin: generated-by-assura
source_files:
  - source-documents/files/sample-source.txt
related_requirements:
  - requirement-agent-content-baseline
checksum_sha256: ""
notes: Replace this generated sample with project-owned source-document metadata.
---

# Source Documents Manifest

Track binary or externally sourced documents here by metadata and local file
references. Assura validates the referenced file paths without reading binary
contents as UTF-8.
"#
}

fn source_document_sample_file() -> &'static str {
    "Generated sample source document placeholder.\n"
}
