//! Static files generated by `assura agent onboard`.

use super::agent_onboarding::DetectedSection;
use super::agent_onboarding_content_templates as content;
use super::agent_onboarding_proposal_sbir_templates as proposal_sbir;
use super::AgentContentTemplate;

pub(super) fn baseline_files(
    detected: &DetectedSection,
    content_template: AgentContentTemplate,
) -> Vec<GeneratedFile> {
    let mut files = vec![
        GeneratedFile {
            path: ".assura/config.yml",
            contents: agent_ready_config(content_template),
            required: true,
            executable: false,
        },
        GeneratedFile::static_file(".assura/presets.lock.yml", presets_lock()),
        GeneratedFile::static_file("AGENTS.md", agents_md()),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/SKILL.md",
            project_maintenance_skill(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/agents/openai.yaml",
            openai_agent_config(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/references/assura-onboarding.md",
            onboarding_reference(),
        ),
        GeneratedFile::static_file("docs/process/agent-workflow.md", agent_workflow_doc()),
        GeneratedFile::static_file("docs/learnings/README.md", learnings_readme()),
        GeneratedFile::static_file(
            ".assura/examples/agent-project/AGENTS.example.md",
            agents_example(),
        ),
        GeneratedFile::static_file(
            ".assura/examples/agent-project/SKILL.example.md",
            skill_example(),
        ),
        GeneratedFile {
            path: ".assura/onboarding/summary.md",
            contents: onboarding_summary(detected),
            required: true,
            executable: false,
        },
        GeneratedFile::static_file(".assura/onboarding/questions.md", onboarding_questions()),
        GeneratedFile::static_file(".assura/onboarding/lifecycle.md", onboarding_lifecycle()),
        GeneratedFile::static_file(
            ".assura/onboarding/agent-next.md",
            agent_next(content_template),
        ),
    ];
    files.extend(content::content_template_files(content_template));
    files
}

#[derive(Clone)]
pub(super) struct GeneratedFile {
    pub(super) path: &'static str,
    pub(super) contents: String,
    pub(super) required: bool,
    pub(super) executable: bool,
}

impl GeneratedFile {
    pub(super) fn static_file(path: &'static str, contents: &'static str) -> Self {
        Self {
            path,
            contents: contents.to_string(),
            required: true,
            executable: false,
        }
    }

    pub(super) fn executable_file(path: &'static str, contents: &'static str) -> Self {
        Self {
            path,
            contents: contents.to_string(),
            required: true,
            executable: true,
        }
    }
}

fn agent_ready_config(content_template: AgentContentTemplate) -> String {
    let repository_references = content::repository_reference_config(content_template);
    let requirements_traceability = content::requirements_traceability_config(content_template);
    let content_config = content::content_config(content_template);
    let root_required_dirs = content::root_required_dirs(content_template);
    let root_structure = content::root_structure(content_template);
    let docs_structure = content::docs_structure(content_template);
    format!(
        r#"version: "2.0"

extensions:
  agent_guidance:
    - id: agent_project_guidance
      severity: low
      agents_path: AGENTS.md
      skill_paths:
        - ".agents/skills/*/SKILL.md"
      required_agents_sections:
        - Operating Rules
        - Process Docs vs Skills
        - Skills
        - Anchors
      required_skill_frontmatter:
        - name
        - description
        - applies_when
      required_skill_sections:
        - Workflow
        - Read as needed
        - Outputs
        - Guardrails
      skill_index_section: Skills
      best_practices_reference: "Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as concise indexes to deeper references."
      skill_routing_section: Skills
      allowed_skill_name_patterns:
        - "assura-*"
        - "assura_*"
      skill_reference_sections:
        - Read as needed
      skill_doc_routing_section: Read as needed
      skill_reference_prefixes:
        - references/
        - scripts/
        - assets/
        - docs/process/
        - .assura/onboarding/
      max_agents_lines: 160
      max_skill_lines: 120
{repository_references}
{requirements_traceability}
{content_config}

rules:
  "@assura-skill-dir":
    SKILL.md: exists:1
    agents/: exists:0-1
    references/: exists:0-1
    scripts/: exists:0-1
    assets/: exists:0-1
    extra: false

structure:
  ./:
    extra: true
    AGENTS.md: exists:1
    README.md: exists:0-1
    ".gitignore": exists:0-1
    Cargo.toml: exists:0-1
    package.json: exists:0-1
    pyproject.toml: exists:0-1
    directories:
      required:
        - ".assura"
        - ".agents"
        - "docs"
{root_required_dirs}
  .assura/:
    required: true
    config.yml: exists:1
    presets.lock.yml: exists:1
    onboarding/: exists:1
    examples/: exists:1
    integrations/: exists:0-1
  .assura/onboarding/:
    required: true
    summary.md: exists:1
    questions.md: exists:1
    lifecycle.md: exists:1
    agent-next.md: exists:1
    doctor.json: exists:1
  .assura/examples/agent-project/:
    required: true
    AGENTS.example.md: exists:1
    SKILL.example.md: exists:1
  .agents/:
    required: true
    skills/: exists:1
  .agents/skills/:
    required: true
    extra: true
    "{{skill}}/":
      use: "@assura-skill-dir"
  docs/:
    required: true
    process/: exists:1
    learnings/: exists:1
{docs_structure}
  docs/process/:
    required: true
    agent-workflow.md: exists:1
  docs/learnings/:
    required: true
    README.md: exists:1
{root_structure}

exclude:
  - ".git/**"
  - "target/**"
  - "node_modules/**"
  - "dist/**"
  - "**/dist/**"
"#
    )
}

fn presets_lock() -> &'static str {
    r#"schema: assura.presets-lock.v1
profile: agent-project
version: 1
generated_by: assura agent onboard
"#
}

fn agents_md() -> &'static str {
    r#"# Agent Instructions

Assura has installed a broad agent-ready baseline for this repository.

## Operating Rules

Before adding project-specific conventions, read
`.assura/onboarding/agent-next.md` and ask the user the remaining
specialization questions. Do not invent language, layout, naming, traceability,
or domain conventions.

Use `assura check --format agent --warn .` for advisory feedback while working.
Use gate-mode checks before push or CI by omitting `--warn`.

## Process Docs vs Skills

Use `docs/process/` for durable process documentation and use project-local
skills for repeatable agent workflows. Keep skill entrypoints concise.
Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as
concise indexes to deeper references.
Reference this best-practice message when editing agent guidance instead of
expanding AGENTS.md with long procedures.

## Skills

| When | Must first load |
| --- | --- |
| Maintaining the broad Assura baseline, onboarding packet, or specialization handoff | [`assura-project-maintenance`](.agents/skills/assura-project-maintenance/SKILL.md) |

## Anchors

Use these section headings as stable anchors for agent routing:
Operating Rules, Process Docs vs Skills, Skills, Anchors.
"#
}

fn project_maintenance_skill() -> &'static str {
    r#"---
name: assura-project-maintenance
description: Maintain the project-local Assura baseline and onboarding packet.
applies_when: Maintaining the Assura baseline, onboarding packet, or specialization handoff.
---

# Assura Project Maintenance

## Workflow

Read `.assura/onboarding/agent-next.md` before specializing this repository.
Use `assura check --format agent --warn .` for advisory feedback while working.

## Read as needed

| When | Read first |
| --- | --- |
| Specializing the broad baseline | `references/assura-onboarding.md` |
| Choosing the next onboarding action | `.assura/onboarding/agent-next.md` |

## Outputs

- Updated Assura baseline files or a concise explanation that no baseline
  update was needed.
- Clear remaining specialization questions for the user.

## Guardrails

- Do not invent project conventions before the user answers specialization
  questions.
- Keep longer examples and runbooks in `references/` or `docs/process/`.
"#
}

fn openai_agent_config() -> &'static str {
    "agent: openai\nprofile: assura-project-maintenance\n"
}

fn onboarding_reference() -> &'static str {
    "# Assura Onboarding\n\nThe broad baseline is active. Specialize only after user answers.\n"
}

fn agent_workflow_doc() -> &'static str {
    r#"---
id: process-agent-workflow
title: Agent Workflow
status: active
related_requirements:
  - requirement-agent-content-baseline
---

# Agent Workflow

Run Assura checks, read agent-next.md, ask before specializing.
"#
}

fn learnings_readme() -> &'static str {
    r#"---
id: learning-agent-lessons
title: Agent Lessons
status: active
related_requirements:
  - requirement-agent-content-baseline
---

# Learnings

Record durable project lessons here when they affect future agent work.
"#
}

fn agents_example() -> &'static str {
    r#"# Agent Instructions Example

## Operating Rules

Replace with project-specific guidance after user answers.

## Process Docs vs Skills

Keep durable process docs in `docs/process/` and executable agent workflows in
project-local skills.
Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as
concise indexes to deeper references.

## Skills

| When | Must first load |
| --- | --- |
| Running a repeatable project-local workflow | [`example-skill`](../../.agents/skills/example-skill/SKILL.md) |

## Anchors

Keep these headings stable for agent routing.
"#
}

fn skill_example() -> &'static str {
    r#"---
name: example-skill
description: Briefly describe the repeatable project-local workflow.
applies_when: Use when the project-local workflow is needed.
---

# Skill Example

## Workflow

Keep SKILL.md concise and put detailed references in subdirectories.

## Read as needed

| When | Read first |
| --- | --- |
| Running the workflow | `references/runbook.md` |

## Outputs

- Name the concrete artifact or status this skill should produce.

## Guardrails

- Move long examples into `references/` or `docs/process/`.
"#
}

fn onboarding_summary(detected: &DetectedSection) -> String {
    format!(
        "# Assura Onboarding Summary\n\nProject type: `{}` ({})\nAgent harness: `{}` ({})\n\nBroad agent-ready baseline is active. Specialization is still pending.\n",
        detected.project_type,
        detected.project_confidence,
        detected.agent_harness,
        detected.agent_confidence
    )
}

fn onboarding_questions() -> &'static str {
    r#"# Assura Onboarding Questions

1. What primary language or stack should this project use?
2. What project type is this: library, app, docs site, proposal, research repo, data project, monorepo, or other?
3. What file naming convention should apply: kebab-case, snake_case, PascalCase, or mixed by folder?
4. What source layout should the project use?
5. What test layout should the project use?
6. Should docs be strict from day one or advisory until the first milestone?
7. Should agent hooks be advisory only while working and blocking only in CI?
8. Are there required files or folders specific to this project?
9. Are there binary or source documents that should be tracked by manifest instead of read as text?
10. Should Assura create typed content models for tasks, decisions, requirements, evidence, or source documents?
"#
}

fn onboarding_lifecycle() -> &'static str {
    r#"# Assura Lifecycle Profiles

Use these modes consistently:

| Mode | When | Blocking | Command |
| --- | --- | --- | --- |
| nudge | During agent working loops and path-aware tool events | no | `assura agent nudge --event before-tool --changed <path> --format json .` |
| warn | Before local commits or while drafting | no | `assura check --format agent --warn --min-severity low --max-issues 10 .` |
| gate | Before push, merge, or CI | yes | `assura check --format agent --min-severity medium --max-issues 20 .` |

Host-agent integrations are reviewable local bundles under
`.assura/integrations/<agent>/`. Assura does not silently mutate global or
host-agent configuration. Run `assura agent integration doctor <agent> .` after
manual host wiring.
"#
}

fn agent_next(content_template: AgentContentTemplate) -> &'static str {
    if matches!(content_template, AgentContentTemplate::ProposalSbir) {
        return proposal_sbir::agent_next();
    }

    r#"# Agent Next

Assura is installed and the broad agent-ready baseline is active.

Do not invent project conventions. Ask the user the remaining specialization
questions before adding language, layout, naming, traceability, content-model,
source-document, hook, or domain-specific rules.

Use `.assura/onboarding/lifecycle.md` to decide between nudge, warn, and gate
feedback. Warn mode is advisory for draft work; gate mode is for pre-push,
merge, or CI checks.

## Ask The User

1. What primary language or stack should this project use?
2. What project type is this: library, app, docs site, proposal, research repo, data project, monorepo, or other?
3. What file naming convention should apply: kebab-case, snake_case, PascalCase, or mixed by folder?
4. What source layout should the project use?
5. What test layout should the project use?
6. Should docs be strict from day one or advisory until the first milestone?
7. Should agent hooks be advisory only while working and blocking only in CI?
8. Are there required files or folders specific to this project?
9. Are there binary or source documents that should be tracked by manifest instead of read as text?
10. Should Assura create typed content models for tasks, decisions, requirements, evidence, or source documents?

## After The User Answers

Record answers in `.assura/onboarding/answers.yml` or equivalent project notes,
then run the later specialization flow when it exists.
"#
}
