//! Shared bundle model for host-agent integration lifecycle commands.

use crate::cli::{AgentIntegrationTarget, AgentNudgeEvent, OutputFormat};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};

pub(super) const MANAGED_MARKER: &str = "Generated by Assura agent integration lifecycle";
pub(super) const MANIFEST_SCHEMA: &str = "assura.agent-integration-manifest.v1";
pub(super) const OUTPUT_SCHEMA: &str = "assura.agent-integration.lifecycle.v1";

pub(super) struct IntegrationBundle {
    pub(super) agent: AgentIntegrationTarget,
    pub(super) project_root: PathBuf,
    pub(super) integration_dir: PathBuf,
}

impl IntegrationBundle {
    pub(super) fn new(agent: AgentIntegrationTarget, project_root: PathBuf) -> Self {
        let integration_dir = project_root
            .join(".assura")
            .join("integrations")
            .join(agent.as_str());
        Self {
            agent,
            project_root,
            integration_dir,
        }
    }

    pub(super) fn is_installed(&self) -> bool {
        self.integration_dir.join("manifest.json").is_file()
    }

    pub(super) fn manifest(&self) -> IntegrationManifest {
        let agent = self.agent.as_str();
        IntegrationManifest {
            schema: MANIFEST_SCHEMA,
            managed_marker: MANAGED_MARKER,
            managed_by: "assura",
            target_agent: agent,
            lifecycle_commands: LifecycleCommands {
                install: format!(
                    "assura agent integration install {agent} {}",
                    quote_path(&self.project_root)
                ),
                update: format!(
                    "assura agent integration update {agent} {}",
                    quote_path(&self.project_root)
                ),
                remove: format!(
                    "assura agent integration remove {agent} {}",
                    quote_path(&self.project_root)
                ),
                status: format!(
                    "assura agent integration status {agent} {}",
                    quote_path(&self.project_root)
                ),
                doctor: format!(
                    "assura agent integration doctor {agent} {}",
                    quote_path(&self.project_root)
                ),
            },
            shared_commands: SharedCommands {
                nudge: format!(
                    "assura agent nudge --agent {agent} --event <event> --changed <path> --format json {}",
                    quote_path(&self.project_root)
                ),
                check: check_command_for(self.agent, &self.project_root),
                daemon_status: format!(
                    "assura daemon status --format json {}",
                    quote_path(&self.project_root)
                ),
                daemon_doctor: format!(
                    "assura daemon doctor --format json {}",
                    quote_path(&self.project_root)
                ),
            },
            event_placements: vec![
                EventPlacement::new(AgentNudgeEvent::SessionStart, "session start or resumed session"),
                EventPlacement::new(AgentNudgeEvent::BeforeTool, "before path-aware edit, move, delete, or shell tool calls"),
                EventPlacement::new(AgentNudgeEvent::AfterTool, "after writes or commands that may change project state"),
                EventPlacement::new(AgentNudgeEvent::FileRead, "before or after high-value file reads"),
                EventPlacement::new(AgentNudgeEvent::Idle, "when a session goes idle or a periodic agent review runs"),
                EventPlacement::new(AgentNudgeEvent::Recovery, "after failed tools, stale daemon state, or context recovery"),
            ],
            files: vec!["manifest.json", "assura-agent.sh", "README.md"],
            logging: LoggingGuidance {
                enabled_by_default: true,
                log_file: ".assura/agent-sessions/nudges.jsonl",
                disable: "ASSURA_AGENT_LOG=0",
                session_id: "ASSURA_AGENT_SESSION_ID",
            },
            host: host_guidance(self.agent),
        }
    }

    pub(super) fn expected_files(&self, manifest: &IntegrationManifest) -> Vec<GeneratedFile> {
        vec![
            GeneratedFile {
                path: self.integration_dir.join("manifest.json"),
                kind: "manifest",
                content: format!(
                    "{}\n",
                    serde_json::to_string_pretty(manifest).unwrap_or_default()
                ),
            },
            GeneratedFile {
                path: self.integration_dir.join("assura-agent.sh"),
                kind: "wrapper",
                content: wrapper_script(self.agent, &self.project_root),
            },
            GeneratedFile {
                path: self.integration_dir.join("README.md"),
                kind: "readme",
                content: readme(self.agent, &self.project_root),
            },
        ]
    }
}

#[derive(Debug, Serialize)]
pub(super) struct IntegrationReport {
    pub(super) schema: &'static str,
    pub(super) action: &'static str,
    pub(super) agent: &'static str,
    pub(super) dry_run: bool,
    pub(super) changed: bool,
    pub(super) installed: bool,
    pub(super) project_root: String,
    pub(super) integration_dir: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) manifest: Option<IntegrationManifest>,
    pub(super) files: Vec<FileAction>,
    pub(super) checks: Vec<DoctorCheck>,
    pub(super) host: HostGuidance,
}

#[derive(Debug, Serialize)]
pub(super) struct IntegrationManifest {
    schema: &'static str,
    managed_marker: &'static str,
    managed_by: &'static str,
    target_agent: &'static str,
    lifecycle_commands: LifecycleCommands,
    shared_commands: SharedCommands,
    event_placements: Vec<EventPlacement>,
    files: Vec<&'static str>,
    logging: LoggingGuidance,
    host: HostGuidance,
}

#[derive(Debug, Serialize)]
struct LifecycleCommands {
    install: String,
    update: String,
    remove: String,
    status: String,
    doctor: String,
}

#[derive(Debug, Serialize)]
struct SharedCommands {
    nudge: String,
    check: String,
    daemon_status: String,
    daemon_doctor: String,
}

#[derive(Debug, Serialize)]
struct EventPlacement {
    event: &'static str,
    placement: &'static str,
}

#[derive(Debug, Serialize)]
struct LoggingGuidance {
    enabled_by_default: bool,
    log_file: &'static str,
    disable: &'static str,
    session_id: &'static str,
}

impl EventPlacement {
    fn new(event: AgentNudgeEvent, placement: &'static str) -> Self {
        let event = match event {
            AgentNudgeEvent::SessionStart => "session-start",
            AgentNudgeEvent::BeforeTool => "before-tool",
            AgentNudgeEvent::AfterTool => "after-tool",
            AgentNudgeEvent::FileRead => "file-read",
            AgentNudgeEvent::Idle => "idle",
            AgentNudgeEvent::Recovery => "recovery",
        };
        Self { event, placement }
    }
}

#[derive(Debug, Serialize)]
pub(super) struct HostGuidance {
    install_mode: &'static str,
    host_config_status: &'static str,
    config_hint: &'static str,
    fallback: &'static str,
}

#[derive(Debug, Serialize)]
pub(super) struct FileAction {
    pub(super) path: String,
    pub(super) kind: &'static str,
    pub(super) action: &'static str,
    pub(super) existed: bool,
    pub(super) managed: bool,
}

#[derive(Debug, Serialize)]
pub(super) struct DoctorCheck {
    pub(super) name: &'static str,
    pub(super) status: CheckStatus,
    pub(super) message: &'static str,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(super) enum CheckStatus {
    Pass,
    Fail,
}

pub(super) struct GeneratedFile {
    pub(super) path: PathBuf,
    pub(super) kind: &'static str,
    pub(super) content: String,
}

pub(super) struct ExistingFile {
    pub(super) managed: bool,
    pub(super) content: Option<String>,
}

pub(super) struct RenderedIntegrationReport {
    pub(super) report: IntegrationReport,
    pub(super) format: OutputFormat,
}

impl RenderedIntegrationReport {
    pub(super) fn render(&self) -> String {
        match self.format {
            OutputFormat::Json => serde_json::to_string_pretty(&self.report).unwrap_or_default(),
            OutputFormat::Yaml => serde_yaml::to_string(&self.report).unwrap_or_default(),
            OutputFormat::Text | OutputFormat::Advice | OutputFormat::Status => {
                let mut lines = vec![
                    format!(
                        "Assura agent integration: {} {}",
                        self.report.action, self.report.agent
                    ),
                    format!("installed={}", self.report.installed),
                    format!("changed={}", self.report.changed),
                    format!("dir={}", self.report.integration_dir),
                ];
                for file in &self.report.files {
                    lines.push(format!("- {} {} {}", file.action, file.kind, file.path));
                }
                for check in &self.report.checks {
                    lines.push(format!(
                        "- doctor {} {:?}: {}",
                        check.name, check.status, check.message
                    ));
                }
                lines.join("\n")
            }
        }
    }
}

pub(super) fn file_status(path: &Path) -> Option<ExistingFile> {
    let content = fs::read_to_string(path).ok()?;
    let managed = content.contains(MANAGED_MARKER);
    Some(ExistingFile {
        managed,
        content: Some(content),
    })
}

pub(super) fn remove_empty_dir(path: &Path) -> Result<(), String> {
    let _ = fs::remove_dir(path);
    Ok(())
}

pub(super) fn set_executable_if_script(path: &Path, kind: &str) -> Result<(), String> {
    if kind != "wrapper" {
        return Ok(());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .map_err(|error| error.to_string())?
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions).map_err(|error| error.to_string())?;
    }
    Ok(())
}

pub(super) fn host_guidance(agent: AgentIntegrationTarget) -> HostGuidance {
    match agent {
        AgentIntegrationTarget::Codex => HostGuidance {
            install_mode: "reviewable-local-bundle",
            host_config_status: "manual-opt-in",
            config_hint: "Wire .assura/integrations/codex/assura-agent.sh or .codex/hooks/assura-agent-nudge.py from approved Codex UserPromptSubmit and PostToolUse hooks.",
            fallback: "Run assura check --format agent --agent codex --warn for prompt-level feedback.",
        },
        AgentIntegrationTarget::Opencode => HostGuidance {
            install_mode: "reviewable-local-bundle",
            host_config_status: "manual-opt-in",
            config_hint: "Call .assura/integrations/opencode/assura-agent.sh from an OpenCode plugin or hook wrapper.",
            fallback: "Run assura agent nudge --agent opencode or assura check --format agent --warn.",
        },
        AgentIntegrationTarget::Claude => HostGuidance {
            install_mode: "reviewable-local-bundle",
            host_config_status: "manual-opt-in",
            config_hint: "Call .assura/integrations/claude/assura-agent.sh from a Claude Code hook or command wrapper.",
            fallback: "Run assura agent nudge --agent claude or assura check --format agent --warn.",
        },
        AgentIntegrationTarget::Pi => HostGuidance {
            install_mode: "reviewable-local-bundle",
            host_config_status: "manual-opt-in",
            config_hint: "Call .assura/integrations/pi/assura-agent.sh from the Pi agent extension or hook layer.",
            fallback: "Run assura agent nudge --agent pi or assura check --format agent --warn.",
        },
    }
}

fn check_command_for(agent: AgentIntegrationTarget, project_root: &Path) -> String {
    match agent {
        AgentIntegrationTarget::Codex => format!(
            "assura check --format agent --agent codex --warn {}",
            quote_path(project_root)
        ),
        _ => format!(
            "assura check --format agent --warn {}",
            quote_path(project_root)
        ),
    }
}

fn wrapper_script(agent: AgentIntegrationTarget, project_root: &Path) -> String {
    let agent = agent.as_str();
    let project_root = quote_path(project_root);
    let check_extra = if agent == "codex" {
        " --agent codex"
    } else {
        ""
    };
    format!(
        r#"#!/bin/sh
# {MANAGED_MARKER}
set -eu

PROJECT_ROOT="${{ASSURA_PROJECT_ROOT:-{project_root}}}"
MODE="${{ASSURA_AGENT_MODE:-nudge}}"
EVENT="${{ASSURA_AGENT_EVENT:-session-start}}"
ASSURA_AGENT_LOG="${{ASSURA_AGENT_LOG:-1}}"
ASSURA_AGENT_LOG_DIR="${{ASSURA_AGENT_LOG_DIR:-$PROJECT_ROOT/.assura/agent-sessions}}"
if [ -z "${{ASSURA_AGENT_SESSION_ID:-}}" ]; then
  ASSURA_AGENT_SESSION_ID="$(date -u +%Y%m%dT%H%M%SZ)-$$"
fi
export ASSURA_AGENT_LOG ASSURA_AGENT_LOG_DIR ASSURA_AGENT_SESSION_ID

run_assura() {{
  if [ -n "${{ASSURA_BIN:-}}" ] && [ -x "$ASSURA_BIN" ]; then
    "$ASSURA_BIN" "$@"
  elif command -v assura >/dev/null 2>&1; then
    assura "$@"
  elif [ -x "$PROJECT_ROOT/target/debug/assura" ]; then
    "$PROJECT_ROOT/target/debug/assura" "$@"
  elif command -v cargo >/dev/null 2>&1; then
    (cd "$PROJECT_ROOT" && cargo run --quiet -- "$@")
  else
    echo "assura command not found and local cargo fallback is unavailable" >&2
    return 127
  fi
}}

case "$MODE" in
  nudge)
    run_assura agent nudge "$PROJECT_ROOT" --agent {agent} --event "$EVENT" --format json "$@"
    ;;
  check)
    run_assura check "$PROJECT_ROOT" --format agent{check_extra} --warn "$@"
    ;;
  daemon-status)
    run_assura daemon status "$PROJECT_ROOT" --format json "$@"
    ;;
  daemon-doctor)
    run_assura daemon doctor "$PROJECT_ROOT" --format json "$@"
    ;;
  *)
    echo "Unsupported ASSURA_AGENT_MODE: $MODE" >&2
    exit 2
    ;;
esac
"#
    )
}

fn readme(agent: AgentIntegrationTarget, project_root: &Path) -> String {
    let agent_name = agent.as_str();
    let check = check_command_for(agent, project_root);
    format!(
        r#"# Assura {agent_name} Integration

{MANAGED_MARKER}

This bundle is reviewable local glue. It does not embed validation logic and it
does not silently mutate host-agent configuration.

## Wrapper

```bash
.assura/integrations/{agent_name}/assura-agent.sh
```

Set `ASSURA_AGENT_MODE` to one of `nudge`, `check`, `daemon-status`, or
`daemon-doctor`. For nudges, set `ASSURA_AGENT_EVENT` to `session-start`,
`before-tool`, `after-tool`, `file-read`, `idle`, or `recovery`.

Set `ASSURA_BIN=/absolute/path/to/assura` when the host hook should use a
specific Assura binary instead of the first `assura` on `PATH`.

## Codex Hooks

For Codex, wire the repo-local adapter from approved `UserPromptSubmit` and
`PostToolUse` hooks. The prompt hook records a baseline and idle nudge. The
post-tool hook records changed-path deltas since the previous prompt/tool
snapshot, calls this wrapper with `ASSURA_AGENT_EVENT=after-tool`, and injects
Codex context only when Assura findings, high-risk Git intent, or large change
pressure make the nudge worth interrupting the model.

## Logging

Wrapper invocations enable Assura nudge logging by default. Each `nudge` call
appends a compact JSONL record to:

```bash
.assura/agent-sessions/nudges.jsonl
```

Set `ASSURA_AGENT_SESSION_ID` in the host integration to group records by agent
session. Set `ASSURA_AGENT_LOG=0` to disable logging or `ASSURA_AGENT_LOG_DIR`
to move the log directory.

## Shared Commands

```bash
assura agent nudge --agent {agent_name} --event session-start --format json {root}
assura agent nudge --agent {agent_name} --event before-tool --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event after-tool --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event file-read --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event idle --format json {root}
assura agent nudge --agent {agent_name} --event recovery --format json {root}
{check}
assura daemon status --format json {root}
assura daemon doctor --format json {root}
```
"#,
        root = quote_path(project_root),
    )
}

pub(super) fn path_string(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(super) fn quote_path(path: &Path) -> String {
    let value = path.display().to_string();
    if value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-'))
    {
        value
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}
