//! Proposal/SBIR domain-pack files generated by `assura agent onboard`.

use crate::cli::agent_onboarding_content_templates::{
    agent_project_content_collections, agent_project_content_relations, content_model_header,
};
use crate::cli::agent_onboarding_document_project_templates as document_project;
use crate::cli::agent_onboarding_proposal_sbir_scripts as scripts;
use crate::cli::agent_onboarding_templates::GeneratedFile;

pub(super) fn content_config() -> String {
    format!(
        "{}{}{}{}{}{}{}",
        content_model_header(),
        agent_project_content_collections(),
        document_project::content_collections(),
        PROPOSAL_SBIR_COLLECTIONS,
        agent_project_content_relations(),
        document_project::content_relations(),
        PROPOSAL_SBIR_RELATIONS
    )
}

pub(super) fn requirements_traceability_config() -> &'static str {
    r#"  requirements_traceability:
    - id: document_project_traceability
      severity: high
      requirements_collection: requirements
      priority_field: priority
      high_priority_values:
        - high
        - critical
      coverage_collections:
        - evidence
        - docs
        - drafts
        - final_docs
        - claims
      claim_collections:
        - claims
      evidence_collections:
        - evidence
      source_document_collections:
        - source_documents
      finding_collections:
        - findings
      owner_fields:
        - owner
      status_fields:
        - status
    - id: proposal_sbir_traceability
      severity: high
      requirements_collection: proposal_requirements
      priority_field: priority
      high_priority_values:
        - high
        - critical
      coverage_collections:
        - proposal_evidence
        - proposal_claims
        - proposal_scorecards
        - proposal_review_findings
        - proposal_package_manifests
        - proposal_submission_checklists
      claim_collections:
        - proposal_claims
      evidence_collections:
        - proposal_evidence
      source_document_collections:
        - source_documents
      finding_collections:
        - proposal_review_findings
      owner_fields:
        - owner
      status_fields:
        - status
  computed_checks:
    - id: proposal_sbir_readiness
      script: ".assura/scripts/proposal-sbir-readiness.sh"
      windows_script: ".assura/scripts/proposal-sbir-readiness.cmd"
      severity: high
      timeout_ms: 5000
"#
}

pub(super) fn root_required_dirs() -> &'static str {
    r#"        - "library"
        - "source-documents"
        - "proposals"
"#
}

pub(super) fn root_structure() -> &'static str {
    r#"  library/:
    required: true
    topics/: exists:1
  library/topics/:
    required: true
    topic-document-project-baseline.md: exists:1
  source-documents/:
    required: true
    manifest.md: exists:1
    files/: exists:1
  .assura/scripts/:
    required: true
    proposal-sbir-readiness.sh: exists:1
    proposal-sbir-readiness.cmd: exists:1
  proposals/:
    required: true
    requirements/: exists:1
    evidence/: exists:1
    claims/: exists:1
    scorecards/: exists:1
    review-findings/: exists:1
    package/: exists:1
    submission/: exists:1
  proposals/requirements/:
    required: true
    requirement-sbir-technical-merit.md: exists:1
  proposals/evidence/:
    required: true
    evidence-sbir-technical-merit.md: exists:1
  proposals/claims/:
    required: true
    claim-sbir-technical-merit.md: exists:1
  proposals/scorecards/:
    required: true
    scorecard-sbir-baseline.md: exists:1
  proposals/review-findings/:
    required: true
    finding-sbir-technical-review.md: exists:1
  proposals/package/:
    required: true
    package-manifest-sbir-baseline.md: exists:1
  proposals/submission/:
    required: true
    submission-checklist-sbir-baseline.md: exists:1
"#
}

pub(super) fn files() -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::executable_file(
            ".assura/scripts/proposal-sbir-readiness.sh",
            scripts::sh_readiness_script(),
        ),
        GeneratedFile::static_file(
            ".assura/scripts/proposal-sbir-readiness.cmd",
            scripts::cmd_readiness_script(),
        ),
        GeneratedFile::static_file(
            "proposals/requirements/requirement-sbir-technical-merit.md",
            requirement_sbir_technical_merit(),
        ),
        GeneratedFile::static_file(
            "proposals/evidence/evidence-sbir-technical-merit.md",
            evidence_sbir_technical_merit(),
        ),
        GeneratedFile::static_file(
            "proposals/claims/claim-sbir-technical-merit.md",
            claim_sbir_technical_merit(),
        ),
        GeneratedFile::static_file(
            "proposals/scorecards/scorecard-sbir-baseline.md",
            scorecard_sbir_baseline(),
        ),
        GeneratedFile::static_file(
            "proposals/review-findings/finding-sbir-technical-review.md",
            finding_sbir_technical_review(),
        ),
        GeneratedFile::static_file(
            "proposals/package/package-manifest-sbir-baseline.md",
            package_manifest_sbir_baseline(),
        ),
        GeneratedFile::static_file(
            "proposals/submission/submission-checklist-sbir-baseline.md",
            submission_checklist_sbir_baseline(),
        ),
    ]
}

pub(super) fn agent_next() -> &'static str {
    r#"# Agent Next

Assura is installed and the proposal/SBIR domain pack is active.

Do not invent sponsor, solicitation, scoring, or submission conventions. Use
the generated proposal records as placeholders until the user replaces them
with project-owned requirements, evidence, source documents, review findings,
and final package metadata.

Use `.assura/onboarding/lifecycle.md` to decide between nudge, warn, and gate
feedback. Warn mode is advisory for draft work; gate mode is for pre-push,
merge, or CI checks.

## Proposal SBIR Workflow

1. Reconcile source-document custody in `source-documents/manifest.md`.
2. Fill missing proposal evidence in `proposals/evidence/`.
3. Resolve open review findings in `proposals/review-findings/`.
4. Update scorecards in `proposals/scorecards/` as human review signals.
5. Verify final package metadata in `proposals/package/` and submission
   checklist records in `proposals/submission/`.

Scores are planning signals for humans. They do not replace proposal judgment,
compliance review, or sponsor-specific submission requirements.

## Ask The User

1. Which solicitation, sponsor, or opportunity does this repository support?
2. What scoring rubric and threshold should proposal reviewers use?
3. What source documents must be tracked by manifest instead of read as text?
4. Who owns final review findings and submission approval?
5. Which portal checklist items are mandatory before submission?

## After The User Answers

Record answers in `.assura/onboarding/answers.yml` or equivalent project notes,
then replace the generated placeholder records with project-owned proposal
facts.
"#
}

const PROPOSAL_SBIR_COLLECTIONS: &str = r#"  proposal_requirements:
    class: ProjectRecord
    path: "proposals/requirements/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_evidence:
    class: ProjectRecord
    path: "proposals/evidence/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_claims:
    class: ProjectRecord
    path: "proposals/claims/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_scorecards:
    class: ProjectRecord
    path: "proposals/scorecards/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_review_findings:
    class: ProjectRecord
    path: "proposals/review-findings/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_package_manifests:
    class: ProjectRecord
    path: "proposals/package/*.md"
    adapter: markdown_frontmatter
    id: id
  proposal_submission_checklists:
    class: ProjectRecord
    path: "proposals/submission/*.md"
    adapter: markdown_frontmatter
    id: id
"#;

const PROPOSAL_SBIR_RELATIONS: &str = r#"  proposal_evidence.requirements:
    target: proposal_requirements
    many: true
  proposal_evidence.source_documents:
    target: source_documents
    many: true
  proposal_claims.requirements:
    target: proposal_requirements
    many: true
  proposal_claims.evidence:
    target: proposal_evidence
    many: true
  proposal_scorecards.requirements:
    target: proposal_requirements
    many: true
  proposal_scorecards.evidence:
    target: proposal_evidence
    many: true
  proposal_review_findings.requirements:
    target: proposal_requirements
    many: true
  proposal_review_findings.evidence:
    target: proposal_evidence
    many: true
  proposal_package_manifests.requirements:
    target: proposal_requirements
    many: true
  proposal_package_manifests.evidence:
    target: proposal_evidence
    many: true
  proposal_package_manifests.source_documents:
    target: source_documents
    many: true
  proposal_package_manifests.final_docs:
    target: final_docs
    many: true
  proposal_submission_checklists.requirements:
    target: proposal_requirements
    many: true
  proposal_submission_checklists.evidence:
    target: proposal_evidence
    many: true
"#;

fn requirement_sbir_technical_merit() -> &'static str {
    r#"---
id: requirement-sbir-technical-merit
title: SBIR Technical Merit Requirement
status: active
priority: critical
summary: The proposal must make technical merit explicit and evidence-backed.
---

# SBIR Technical Merit Requirement

Use proposal requirements for solicitation-specific obligations that need
evidence, scoring, review, and final package traceability.
"#
}

fn evidence_sbir_technical_merit() -> &'static str {
    r#"---
id: evidence-sbir-technical-merit
title: SBIR Technical Merit Evidence
status: active
requirements:
  - requirement-sbir-technical-merit
source_documents:
  - source-documents-manifest
summary: Starter evidence linked to source-document custody metadata.
---

# SBIR Technical Merit Evidence

Replace this starter evidence with project-owned substantiation for the
technical merit requirement.
"#
}

fn claim_sbir_technical_merit() -> &'static str {
    r#"---
id: claim-sbir-technical-merit
title: SBIR Technical Merit Claim
status: active
requirements:
  - requirement-sbir-technical-merit
evidence:
  - evidence-sbir-technical-merit
summary: Starter claim that remains traceable to proposal evidence.
---

# SBIR Technical Merit Claim

Use claims for reviewer-facing statements that should be backed by explicit
evidence instead of rediscovered from prose.
"#
}

fn scorecard_sbir_baseline() -> &'static str {
    r#"---
id: scorecard-sbir-baseline
title: SBIR Baseline Scorecard
status: ready
requirements:
  - requirement-sbir-technical-merit
evidence:
  - evidence-sbir-technical-merit
weighted_score: 85
threshold_score: 70
confidence: medium
summary: Starter weighted scorecard for proposal review readiness.
---

# SBIR Baseline Scorecard

Scores are planning signals for humans. They do not replace proposal judgment,
compliance review, or sponsor-specific submission requirements.
"#
}

fn finding_sbir_technical_review() -> &'static str {
    r#"---
id: finding-sbir-technical-review
title: SBIR Technical Review Finding
status: resolved
owner: proposal-lead
requirements:
  - requirement-sbir-technical-merit
evidence:
  - evidence-sbir-technical-merit
summary: Starter review finding showing how proposal review closure is tracked.
---

# SBIR Technical Review Finding

Record proposal review findings here and keep unresolved findings visible until
the package is ready.
"#
}

fn package_manifest_sbir_baseline() -> &'static str {
    r#"---
id: package-manifest-sbir-baseline
title: SBIR Final Package Manifest
status: ready
requirements:
  - requirement-sbir-technical-merit
evidence:
  - evidence-sbir-technical-merit
source_documents:
  - source-documents-manifest
final_docs:
  - final-document-project-baseline
final_package_path: docs/final/final-document-project-baseline.md
summary: Starter final package manifest for proposal submission readiness.
---

# SBIR Final Package Manifest

Track the final package by metadata and repository path. Assura validates the
manifest and links without parsing PDF or DOCX contents.
"#
}

fn submission_checklist_sbir_baseline() -> &'static str {
    r#"---
id: submission-checklist-sbir-baseline
title: SBIR Submission Checklist
status: ready
requirements:
  - requirement-sbir-technical-merit
evidence:
  - evidence-sbir-technical-merit
portal_ready: true
deadline_confirmed: true
summary: Starter checklist for portal and deadline readiness.
---

# SBIR Submission Checklist

Use this record for sponsor portal, deadline, attachment, and final human
submission checks.
"#
}
