//! Optional content runtime files generated by `assura agent onboard`.

use super::agent_onboarding_document_project_templates as document_project;
use super::agent_onboarding_templates::GeneratedFile;
use crate::cli::AgentContentTemplate;

pub(super) fn repository_reference_config(template: AgentContentTemplate) -> &'static str {
    if matches!(template, AgentContentTemplate::DocumentProject) {
        r#"  repository_references:
    - id: source_document_files
      paths:
        - "source-documents/*.md"
      frontmatter_fields:
        - source_files
      severity: high
"#
    } else {
        ""
    }
}

pub(super) fn content_config(template: AgentContentTemplate) -> String {
    match template {
        AgentContentTemplate::None => String::new(),
        AgentContentTemplate::AgentProject => agent_project_content_config(),
        AgentContentTemplate::DocumentProject => document_project::content_config(),
    }
}

pub(super) fn root_required_dirs(template: AgentContentTemplate) -> &'static str {
    if matches!(template, AgentContentTemplate::DocumentProject) {
        document_project::root_required_dirs()
    } else {
        ""
    }
}

pub(super) fn root_structure(template: AgentContentTemplate) -> &'static str {
    if matches!(template, AgentContentTemplate::DocumentProject) {
        document_project::root_structure()
    } else {
        ""
    }
}

pub(super) fn docs_structure(template: AgentContentTemplate) -> &'static str {
    if matches!(template, AgentContentTemplate::DocumentProject) {
        document_project::docs_structure()
    } else {
        ""
    }
}

pub(super) fn content_template_files(template: AgentContentTemplate) -> Vec<GeneratedFile> {
    match template {
        AgentContentTemplate::None => Vec::new(),
        AgentContentTemplate::AgentProject => agent_project_content_files(),
        AgentContentTemplate::DocumentProject => {
            let mut files = agent_project_content_files();
            files.extend(document_project::files());
            files
        }
    }
}

fn agent_project_content_files() -> Vec<GeneratedFile> {
    vec![
        GeneratedFile::static_file(
            ".assura/models/agent-project/baseline.schema.json",
            agent_project_schema(),
        ),
        GeneratedFile::static_file(
            "docs/requirements/requirement-agent-content-baseline.md",
            requirement_agent_content_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/tasks/task-agent-content-baseline.md",
            task_agent_content_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/evidence/evidence-agent-content-baseline.md",
            evidence_agent_content_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/decisions/decision-agent-content-baseline.md",
            decision_agent_content_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/findings/finding-agent-content-baseline.md",
            finding_agent_content_baseline(),
        ),
        GeneratedFile::static_file(
            "docs/project-docs/doc-agent-content-baseline.md",
            doc_agent_content_baseline(),
        ),
    ]
}

pub(super) fn agent_project_content_config() -> String {
    format!("{CONTENT_MODEL_HEADER}{AGENT_PROJECT_COLLECTIONS}{AGENT_PROJECT_RELATIONS}")
}

const CONTENT_MODEL_HEADER: &str = r#"
models:
  validation_artifact: ".assura/models/agent-project/baseline.schema.json"

collections:
"#;

const AGENT_PROJECT_COLLECTIONS: &str = r#"  decisions:
    class: Decision
    path: "docs/decisions/*.md"
    adapter: markdown_frontmatter
    id: id
  tasks:
    class: Task
    path: "docs/tasks/*.md"
    adapter: markdown_frontmatter
    id: id
  requirements:
    class: Requirement
    path: "docs/requirements/*.md"
    adapter: markdown_frontmatter
    id: id
  evidence:
    class: Evidence
    path: "docs/evidence/*.md"
    adapter: markdown_frontmatter
    id: id
  docs:
    class: Doc
    path: "docs/project-docs/*.md"
    adapter: markdown_frontmatter
    id: id
  findings:
    class: Finding
    path: "docs/findings/*.md"
    adapter: markdown_frontmatter
    id: id
  skills:
    class: Skill
    path: ".agents/skills/*/SKILL.md"
    adapter: markdown_frontmatter
    id: name
  processes:
    class: Process
    path: "docs/process/*.md"
    adapter: markdown_frontmatter
    id: id
  learnings:
    class: Learning
    path: "docs/learnings/*.md"
    adapter: markdown_frontmatter
    id: id
"#;

const AGENT_PROJECT_RELATIONS: &str = r#"
relations:
  decisions.requirements:
    target: requirements
    many: true
  tasks.requirements:
    target: requirements
    many: true
  evidence.requirements:
    target: requirements
    many: true
  docs.requirements:
    target: requirements
    many: true
  findings.evidence:
    target: evidence
    many: true
  processes.related_requirements:
    target: requirements
    many: true
  learnings.related_requirements:
    target: requirements
    many: true
"#;

pub(super) fn agent_project_content_collections() -> &'static str {
    AGENT_PROJECT_COLLECTIONS
}

pub(super) fn agent_project_content_relations() -> &'static str {
    AGENT_PROJECT_RELATIONS
}

pub(super) fn content_model_header() -> &'static str {
    CONTENT_MODEL_HEADER
}

fn agent_project_schema() -> &'static str {
    r##"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$defs": {
    "Decision": { "$ref": "#/$defs/ProjectRecord" },
    "Task": { "$ref": "#/$defs/ProjectRecord" },
    "Requirement": { "$ref": "#/$defs/ProjectRecord" },
    "Evidence": { "$ref": "#/$defs/ProjectRecord" },
    "Doc": { "$ref": "#/$defs/ProjectRecord" },
    "Finding": { "$ref": "#/$defs/ProjectRecord" },
    "Process": { "$ref": "#/$defs/ProjectRecord" },
    "Learning": { "$ref": "#/$defs/ProjectRecord" },
    "Topic": { "$ref": "#/$defs/ProjectRecord" },
    "Draft": { "$ref": "#/$defs/ProjectRecord" },
    "FinalDocument": { "$ref": "#/$defs/ProjectRecord" },
    "Skill": {
      "type": "object",
      "required": ["name", "description", "applies_when"],
      "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "applies_when": { "type": "string" }
      },
      "additionalProperties": true
    },
    "SourceDocument": {
      "type": "object",
      "required": ["id", "title", "status", "kind", "origin", "source_files"],
      "properties": {
        "id": { "type": "string" },
        "title": { "type": "string" },
        "status": { "type": "string" },
        "kind": { "type": "string" },
        "origin": { "type": "string" },
        "source_files": {
          "type": "array",
          "items": { "type": "string" }
        },
        "related_requirements": {
          "type": "array",
          "items": { "type": "string" }
        },
        "notes": { "type": "string" }
      },
      "additionalProperties": true
    },
    "ProjectRecord": {
      "type": "object",
      "required": ["id", "title", "status"],
      "properties": {
        "id": { "type": "string" },
        "title": { "type": "string" },
        "status": { "type": "string" },
        "requirements": {
          "type": "array",
          "items": { "type": "string" }
        },
        "related_requirements": {
          "type": "array",
          "items": { "type": "string" }
        },
        "evidence": {
          "type": "array",
          "items": { "type": "string" }
        },
        "summary": { "type": "string" }
      },
      "additionalProperties": true
    }
  }
}
"##
}

fn requirement_agent_content_baseline() -> &'static str {
    r#"---
id: requirement-agent-content-baseline
title: Agent Content Baseline Requirement
status: active
summary: Agent-ready projects should make modeled project facts explicit when content is activated.
---

# Agent Content Baseline Requirement

This starter requirement proves that activated content models can hold
repo-native project facts without adding domain-specific proposal behavior.
"#
}

fn task_agent_content_baseline() -> &'static str {
    r#"---
id: task-agent-content-baseline
title: Activate Agent Content Baseline
status: active
requirements:
  - requirement-agent-content-baseline
---

# Activate Agent Content Baseline

Use this task as the first modeled work item for the activated agent-project
content template.
"#
}

fn evidence_agent_content_baseline() -> &'static str {
    r#"---
id: evidence-agent-content-baseline
title: Agent Content Baseline Evidence
status: active
requirements:
  - requirement-agent-content-baseline
---

# Agent Content Baseline Evidence

This file proves the content runtime can index evidence linked to a
requirement.
"#
}

fn decision_agent_content_baseline() -> &'static str {
    r#"---
id: decision-agent-content-baseline
title: Use Repo-Native Agent Content Models
status: accepted
requirements:
  - requirement-agent-content-baseline
---

# Use Repo-Native Agent Content Models

The baseline uses Markdown frontmatter and checked-in schema artifacts so agents
can inspect and specialize the project facts locally.
"#
}

fn finding_agent_content_baseline() -> &'static str {
    r#"---
id: finding-agent-content-baseline
title: Agent Content Baseline Finding
status: open
evidence:
  - evidence-agent-content-baseline
---

# Agent Content Baseline Finding

Activated content should make checked evidence links visible to agents.
"#
}

fn doc_agent_content_baseline() -> &'static str {
    r#"---
id: doc-agent-content-baseline
title: Agent Content Baseline Doc
status: active
requirements:
  - requirement-agent-content-baseline
---

# Agent Content Baseline Doc

Project docs can be modeled as ordinary repo-native records when that helps
agents discover current source-of-truth material.
"#
}
