//! Shared bundle model for host-agent integration lifecycle commands.

use crate::cli::{AgentIntegrationTarget, AgentNudgeEvent, OutputFormat};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::{Path, PathBuf};

use super::templates::{opencode_plugin, pi_extension, python_hook, wrapper_script};

pub(super) const MANAGED_MARKER: &str = "Generated by Assura agent integration lifecycle";
pub(super) const MANIFEST_SCHEMA: &str = "assura.agent-integration-manifest.v1";
pub(super) const OUTPUT_SCHEMA: &str = "assura.agent-integration.lifecycle.v1";

pub(super) struct IntegrationBundle {
    pub(super) agent: AgentIntegrationTarget,
    pub(super) project_root: PathBuf,
    pub(super) integration_dir: PathBuf,
}

impl IntegrationBundle {
    pub(super) fn new(agent: AgentIntegrationTarget, project_root: PathBuf) -> Self {
        let integration_dir = project_root
            .join(".assura")
            .join("integrations")
            .join(agent.as_str());
        Self {
            agent,
            project_root,
            integration_dir,
        }
    }

    pub(super) fn is_installed(&self) -> bool {
        self.integration_dir.join("manifest.json").is_file()
    }

    pub(super) fn manifest(&self) -> IntegrationManifest {
        let agent = self.agent.as_str();
        IntegrationManifest {
            schema: MANIFEST_SCHEMA,
            assura_version: env!("CARGO_PKG_VERSION"),
            minimum_assura_version: env!("CARGO_PKG_VERSION"),
            adapter_contract_version: 1,
            adapter_version: env!("CARGO_PKG_VERSION"),
            managed_marker: MANAGED_MARKER,
            managed_by: "assura",
            target_agent: agent,
            lifecycle_commands: LifecycleCommands {
                install: format!(
                    "assura agent integration install {agent} {}",
                    quote_path(&self.project_root)
                ),
                update: format!(
                    "assura agent integration update {agent} {}",
                    quote_path(&self.project_root)
                ),
                activate: format!(
                    "assura agent integration activate {agent} {}",
                    quote_path(&self.project_root)
                ),
                deactivate: format!(
                    "assura agent integration deactivate {agent} {}",
                    quote_path(&self.project_root)
                ),
                remove: format!(
                    "assura agent integration remove {agent} {}",
                    quote_path(&self.project_root)
                ),
                status: format!(
                    "assura agent integration status {agent} {}",
                    quote_path(&self.project_root)
                ),
                doctor: format!(
                    "assura agent integration doctor {agent} {}",
                    quote_path(&self.project_root)
                ),
            },
            shared_commands: SharedCommands {
                nudge: format!(
                    "assura agent nudge --agent {agent} --event <event> --changed <path> --format json {}",
                    quote_path(&self.project_root)
                ),
                check: check_command_for(self.agent, &self.project_root),
                daemon_status: format!(
                    "assura daemon status --format json {}",
                    quote_path(&self.project_root)
                ),
                daemon_doctor: format!(
                    "assura daemon doctor --format json {}",
                    quote_path(&self.project_root)
                ),
            },
            event_placements: vec![
                EventPlacement::new(AgentNudgeEvent::SessionStart, "session start or resumed session"),
                EventPlacement::new(AgentNudgeEvent::BeforeTool, "before path-aware edit, move, delete, or shell tool calls"),
                EventPlacement::new(AgentNudgeEvent::AfterTool, "after writes or commands that may change project state"),
                EventPlacement::new(AgentNudgeEvent::FileRead, "before or after high-value file reads"),
                EventPlacement::new(AgentNudgeEvent::Idle, "when a session goes idle or a periodic agent review runs"),
                EventPlacement::new(AgentNudgeEvent::Recovery, "after failed tools, stale daemon state, or context recovery"),
            ],
            event_mappings: event_mappings(self.agent),
            unsupported_events: unsupported_events(self.agent),
            managed_files: self.managed_file_records(),
            logging: LoggingGuidance {
                enabled_by_default: true,
                log_file: ".assura/agent-sessions/nudges.jsonl",
                disable: "ASSURA_AGENT_LOG=0",
                session_id: "ASSURA_AGENT_SESSION_ID",
            },
            runtime: runtime_contract(self.agent),
            host: host_guidance(self.agent),
        }
    }

    pub(super) fn expected_files(&self, manifest: &IntegrationManifest) -> Vec<GeneratedFile> {
        let mut files = vec![
            GeneratedFile {
                path: self.integration_dir.join("manifest.json"),
                kind: "manifest",
                content: format!(
                    "{}\n",
                    serde_json::to_string_pretty(manifest).unwrap_or_default()
                ),
            },
            GeneratedFile {
                path: self.integration_dir.join("assura-agent.sh"),
                kind: "wrapper",
                content: wrapper_script(self.agent, &self.project_root),
            },
            GeneratedFile {
                path: self.integration_dir.join("README.md"),
                kind: "readme",
                content: readme(self.agent, &self.project_root),
            },
        ];
        if matches!(
            self.agent,
            AgentIntegrationTarget::Codex | AgentIntegrationTarget::Claude
        ) {
            files.push(GeneratedFile {
                path: self.integration_dir.join("assura-hook.py"),
                kind: "host_adapter",
                content: python_hook(self.agent),
            });
        }
        files
    }

    pub(super) fn activation_files(&self) -> Vec<GeneratedFile> {
        match self.agent {
            AgentIntegrationTarget::Codex | AgentIntegrationTarget::Claude => Vec::new(),
            AgentIntegrationTarget::Opencode => vec![GeneratedFile {
                path: self.project_root.join(".opencode/plugins/assura.js"),
                kind: "host_activation",
                content: opencode_plugin(),
            }],
            AgentIntegrationTarget::Pi => vec![GeneratedFile {
                path: self.project_root.join(".pi/extensions/assura.ts"),
                kind: "host_activation",
                content: pi_extension(),
            }],
        }
    }

    fn managed_file_records(&self) -> Vec<ManagedFileRecord> {
        let agent = self.agent.as_str();
        let mut files = vec![
            ManagedFileRecord::new(
                format!(".assura/integrations/{agent}/assura-agent.sh"),
                "wrapper",
                &wrapper_script(self.agent, &self.project_root),
                true,
                false,
            ),
            ManagedFileRecord::new(
                format!(".assura/integrations/{agent}/README.md"),
                "readme",
                &readme(self.agent, &self.project_root),
                false,
                false,
            ),
        ];
        if matches!(
            self.agent,
            AgentIntegrationTarget::Codex | AgentIntegrationTarget::Claude
        ) {
            files.push(ManagedFileRecord::new(
                format!(".assura/integrations/{agent}/assura-hook.py"),
                "host_adapter",
                &python_hook(self.agent),
                false,
                false,
            ));
        }
        for file in self.activation_files() {
            files.push(ManagedFileRecord::new(
                relative_to_project(&self.project_root, &file.path),
                file.kind,
                &file.content,
                false,
                true,
            ));
        }
        files
    }
}

#[derive(Debug, Serialize)]
pub(super) struct IntegrationReport {
    pub(super) schema: &'static str,
    pub(super) action: &'static str,
    pub(super) agent: &'static str,
    pub(super) dry_run: bool,
    pub(super) changed: bool,
    pub(super) installed: bool,
    pub(super) project_root: String,
    pub(super) integration_dir: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub(super) manifest: Option<IntegrationManifest>,
    pub(super) files: Vec<FileAction>,
    pub(super) checks: Vec<DoctorCheck>,
    pub(super) activation: ActivationReport,
    pub(super) host: HostGuidance,
}

#[derive(Clone, Debug, Serialize)]
pub(super) struct ActivationReport {
    pub(super) generated: bool,
    pub(super) activated: bool,
    pub(super) verified: bool,
    pub(super) conflicted: bool,
    pub(super) config_path: String,
    pub(super) events: Vec<&'static str>,
    pub(super) verification_scope: &'static str,
    pub(super) host_approval_required: bool,
}

#[derive(Debug, Serialize)]
pub(super) struct IntegrationManifest {
    schema: &'static str,
    assura_version: &'static str,
    minimum_assura_version: &'static str,
    adapter_contract_version: u32,
    adapter_version: &'static str,
    managed_marker: &'static str,
    managed_by: &'static str,
    target_agent: &'static str,
    lifecycle_commands: LifecycleCommands,
    shared_commands: SharedCommands,
    event_placements: Vec<EventPlacement>,
    event_mappings: Vec<HostEventMapping>,
    unsupported_events: Vec<&'static str>,
    managed_files: Vec<ManagedFileRecord>,
    logging: LoggingGuidance,
    runtime: RuntimeContract,
    host: HostGuidance,
}

#[derive(Debug, Serialize)]
struct LifecycleCommands {
    install: String,
    activate: String,
    update: String,
    deactivate: String,
    remove: String,
    status: String,
    doctor: String,
}

#[derive(Debug, Serialize)]
struct SharedCommands {
    nudge: String,
    check: String,
    daemon_status: String,
    daemon_doctor: String,
}

#[derive(Debug, Serialize)]
struct EventPlacement {
    event: &'static str,
    placement: &'static str,
}

#[derive(Debug, Serialize)]
struct HostEventMapping {
    host_event: &'static str,
    assura_event: &'static str,
    delivery: &'static str,
}

#[derive(Debug, Serialize)]
struct ManagedFileRecord {
    path: String,
    kind: &'static str,
    sha256: String,
    executable: bool,
    host_activation: bool,
}

impl ManagedFileRecord {
    fn new(
        path: String,
        kind: &'static str,
        content: &str,
        executable: bool,
        host_activation: bool,
    ) -> Self {
        Self {
            path,
            kind,
            sha256: sha256_hex(content),
            executable,
            host_activation,
        }
    }
}

#[derive(Debug, Serialize)]
struct RuntimeContract {
    adapter_runtime: &'static str,
    host_contract: &'static str,
    host_approval_required: bool,
    verification_scope: &'static str,
    update_channel: &'static str,
}

#[derive(Debug, Serialize)]
struct LoggingGuidance {
    enabled_by_default: bool,
    log_file: &'static str,
    disable: &'static str,
    session_id: &'static str,
}

impl EventPlacement {
    fn new(event: AgentNudgeEvent, placement: &'static str) -> Self {
        let event = match event {
            AgentNudgeEvent::SessionStart => "session-start",
            AgentNudgeEvent::BeforeTool => "before-tool",
            AgentNudgeEvent::AfterTool => "after-tool",
            AgentNudgeEvent::FileRead => "file-read",
            AgentNudgeEvent::Idle => "idle",
            AgentNudgeEvent::Recovery => "recovery",
        };
        Self { event, placement }
    }
}

fn event_mappings(agent: AgentIntegrationTarget) -> Vec<HostEventMapping> {
    match agent {
        AgentIntegrationTarget::Codex => vec![
            host_event("SessionStart", "session-start", "model-context"),
            host_event("UserPromptSubmit", "idle", "model-context"),
            host_event("PreToolUse", "before-tool", "model-context"),
            host_event("PostToolUse", "after-tool", "model-context"),
        ],
        AgentIntegrationTarget::Claude => vec![
            host_event("SessionStart", "session-start", "model-context"),
            host_event("UserPromptSubmit", "idle", "model-context"),
            host_event("PreToolUse", "before-tool", "model-context"),
            host_event("PostToolUse", "after-tool", "model-context"),
            host_event("PostToolUseFailure", "recovery", "model-context"),
        ],
        AgentIntegrationTarget::Opencode => vec![
            host_event("session.created", "session-start", "session-log"),
            host_event("session.idle", "idle", "session-log"),
            host_event("session.error", "recovery", "session-log"),
            host_event("tool.execute.after", "after-tool", "tool-output-context"),
        ],
        AgentIntegrationTarget::Pi => vec![
            host_event("session_start", "session-start", "session-log"),
            host_event("before_agent_start", "idle", "model-context"),
            host_event("tool_result", "after-tool", "tool-result-context"),
        ],
    }
}

fn host_event(
    host_event: &'static str,
    assura_event: &'static str,
    delivery: &'static str,
) -> HostEventMapping {
    HostEventMapping {
        host_event,
        assura_event,
        delivery,
    }
}

fn unsupported_events(agent: AgentIntegrationTarget) -> Vec<&'static str> {
    match agent {
        AgentIntegrationTarget::Codex => vec!["file-read", "recovery"],
        AgentIntegrationTarget::Claude => vec!["file-read"],
        AgentIntegrationTarget::Opencode => vec!["before-tool", "file-read"],
        AgentIntegrationTarget::Pi => vec!["before-tool", "file-read", "recovery"],
    }
}

fn runtime_contract(agent: AgentIntegrationTarget) -> RuntimeContract {
    match agent {
        AgentIntegrationTarget::Codex => RuntimeContract {
            adapter_runtime: "python3",
            host_contract: "project hooks.json command hooks",
            host_approval_required: host_approval_required(agent),
            verification_scope: "managed files and project configuration",
            update_channel: "assura agent integration update codex",
        },
        AgentIntegrationTarget::Claude => RuntimeContract {
            adapter_runtime: "python3",
            host_contract: "project settings.json command hooks",
            host_approval_required: host_approval_required(agent),
            verification_scope: "managed files and project configuration",
            update_channel: "assura agent integration update claude",
        },
        AgentIntegrationTarget::Opencode => RuntimeContract {
            adapter_runtime: "host JavaScript runtime",
            host_contract: "project .opencode/plugins JavaScript module",
            host_approval_required: host_approval_required(agent),
            verification_scope: "managed files and project plugin module",
            update_channel: "assura agent integration update opencode",
        },
        AgentIntegrationTarget::Pi => RuntimeContract {
            adapter_runtime: "host TypeScript runtime",
            host_contract: "project .pi/extensions TypeScript module",
            host_approval_required: host_approval_required(agent),
            verification_scope: "managed files and project extension module",
            update_channel: "assura agent integration update pi",
        },
    }
}

pub(super) fn host_approval_required(agent: AgentIntegrationTarget) -> bool {
    !matches!(agent, AgentIntegrationTarget::Opencode)
}

fn sha256_hex(content: &str) -> String {
    format!("{:x}", Sha256::digest(content.as_bytes()))
}

fn relative_to_project(project_root: &Path, path: &Path) -> String {
    path.strip_prefix(project_root)
        .map(path_string)
        .unwrap_or_else(|_| path_string(path))
}

#[derive(Debug, Serialize)]
pub(super) struct HostGuidance {
    install_mode: &'static str,
    host_config_status: &'static str,
    config_hint: &'static str,
    fallback: &'static str,
}

#[derive(Debug, Serialize)]
pub(super) struct FileAction {
    pub(super) path: String,
    pub(super) kind: &'static str,
    pub(super) action: &'static str,
    pub(super) existed: bool,
    pub(super) managed: bool,
}

#[derive(Debug, Serialize)]
pub(super) struct DoctorCheck {
    pub(super) name: &'static str,
    pub(super) status: CheckStatus,
    pub(super) message: &'static str,
}

#[derive(Debug, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub(super) enum CheckStatus {
    Pass,
    Fail,
}

pub(super) struct GeneratedFile {
    pub(super) path: PathBuf,
    pub(super) kind: &'static str,
    pub(super) content: String,
}

pub(super) struct ExistingFile {
    pub(super) managed: bool,
    pub(super) content: Option<String>,
}

pub(super) struct RenderedIntegrationReport {
    pub(super) report: IntegrationReport,
    pub(super) format: OutputFormat,
}

impl RenderedIntegrationReport {
    pub(super) fn render(&self) -> String {
        match self.format {
            OutputFormat::Json => serde_json::to_string_pretty(&self.report).unwrap_or_default(),
            OutputFormat::Yaml => serde_yaml::to_string(&self.report).unwrap_or_default(),
            OutputFormat::Text | OutputFormat::Advice | OutputFormat::Status => {
                let mut lines = vec![
                    format!(
                        "Assura agent integration: {} {}",
                        self.report.action, self.report.agent
                    ),
                    format!("installed={}", self.report.installed),
                    format!("changed={}", self.report.changed),
                    format!("dir={}", self.report.integration_dir),
                    format!(
                        "activation=generated:{} activated:{} verified:{} conflicted:{}",
                        self.report.activation.generated,
                        self.report.activation.activated,
                        self.report.activation.verified,
                        self.report.activation.conflicted
                    ),
                ];
                for file in &self.report.files {
                    lines.push(format!("- {} {} {}", file.action, file.kind, file.path));
                }
                for check in &self.report.checks {
                    lines.push(format!(
                        "- doctor {} {:?}: {}",
                        check.name, check.status, check.message
                    ));
                }
                lines.join("\n")
            }
        }
    }
}

pub(super) fn file_status(path: &Path) -> Option<ExistingFile> {
    let content = fs::read_to_string(path).ok()?;
    let managed = content.contains(MANAGED_MARKER);
    Some(ExistingFile {
        managed,
        content: Some(content),
    })
}

pub(super) fn remove_empty_dir(path: &Path) -> Result<(), String> {
    let _ = fs::remove_dir(path);
    Ok(())
}

pub(super) fn set_executable_if_script(path: &Path, kind: &str) -> Result<(), String> {
    if kind != "wrapper" {
        return Ok(());
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut permissions = fs::metadata(path)
            .map_err(|error| error.to_string())?
            .permissions();
        permissions.set_mode(0o755);
        fs::set_permissions(path, permissions).map_err(|error| error.to_string())?;
    }
    Ok(())
}

pub(super) fn host_guidance(agent: AgentIntegrationTarget) -> HostGuidance {
    match agent {
        AgentIntegrationTarget::Codex => HostGuidance {
            install_mode: "managed-project-lifecycle",
            host_config_status: "explicit-activation",
            config_hint: "Run `assura agent integration activate codex .`; then trust the project and approve its hooks in Codex.",
            fallback: "Run assura check --format agent --agent codex --warn for prompt-level feedback.",
        },
        AgentIntegrationTarget::Opencode => HostGuidance {
            install_mode: "managed-project-lifecycle",
            host_config_status: "explicit-activation",
            config_hint: "Run `assura agent integration activate opencode .`; then trust the project plugin in OpenCode.",
            fallback: "Run assura agent nudge --agent opencode or assura check --format agent --warn.",
        },
        AgentIntegrationTarget::Claude => HostGuidance {
            install_mode: "managed-project-lifecycle",
            host_config_status: "explicit-activation",
            config_hint: "Run `assura agent integration activate claude .`; then trust the project hooks in Claude Code.",
            fallback: "Run assura agent nudge --agent claude or assura check --format agent --warn.",
        },
        AgentIntegrationTarget::Pi => HostGuidance {
            install_mode: "managed-project-lifecycle",
            host_config_status: "explicit-activation",
            config_hint: "Run `assura agent integration activate pi .`; then trust the project extension in Pi.",
            fallback: "Run assura agent nudge --agent pi or assura check --format agent --warn.",
        },
    }
}

fn check_command_for(agent: AgentIntegrationTarget, project_root: &Path) -> String {
    match agent {
        AgentIntegrationTarget::Codex => format!(
            "assura check --format agent --agent codex --warn {}",
            quote_path(project_root)
        ),
        _ => format!(
            "assura check --format agent --warn {}",
            quote_path(project_root)
        ),
    }
}

fn readme(agent: AgentIntegrationTarget, project_root: &Path) -> String {
    let agent_name = agent.as_str();
    let check = check_command_for(agent, project_root);
    format!(
        r#"# Assura {agent_name} Integration

{MANAGED_MARKER}

This bundle is reviewable local glue and does not embed validation logic.
Installation writes only the bundle. Explicit activation patches only
Assura-owned project host configuration; host trust remains under user control.

## Wrapper

```bash
.assura/integrations/{agent_name}/assura-agent.sh
```

Set `ASSURA_AGENT_MODE` to one of `nudge`, `check`, `daemon-status`, or
`daemon-doctor`. For nudges, set `ASSURA_AGENT_EVENT` to `session-start`,
`before-tool`, `after-tool`, `file-read`, `idle`, or `recovery`.

Set `ASSURA_BIN=/absolute/path/to/assura` when the host hook should use a
specific Assura binary instead of the first `assura` on `PATH`.

## Codex Hooks

For Codex, wire the repo-local adapter from approved `UserPromptSubmit` and
`PostToolUse` hooks. The prompt hook records a baseline and idle nudge. The
post-tool hook records changed-path deltas since the previous prompt/tool
snapshot, calls this wrapper with `ASSURA_AGENT_EVENT=after-tool`, and injects
Codex context only when Assura findings, high-risk Git intent, or large change
pressure make the nudge worth interrupting the model.

## Logging

Wrapper invocations enable Assura nudge logging by default. Each `nudge` call
appends a compact JSONL record to:

```bash
.assura/agent-sessions/nudges.jsonl
```

Set `ASSURA_AGENT_SESSION_ID` in the host integration to group records by agent
session. Set `ASSURA_AGENT_LOG=0` to disable logging or `ASSURA_AGENT_LOG_DIR`
to move the log directory.

## Shared Commands

```bash
assura agent nudge --agent {agent_name} --event session-start --format json {root}
assura agent nudge --agent {agent_name} --event before-tool --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event after-tool --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event file-read --changed <path> --format json {root}
assura agent nudge --agent {agent_name} --event idle --format json {root}
assura agent nudge --agent {agent_name} --event recovery --format json {root}
{check}
assura daemon status --format json {root}
assura daemon doctor --format json {root}
```
"#,
        root = quote_path(project_root),
    )
}

pub(super) fn path_string(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

pub(super) fn quote_path(path: &Path) -> String {
    let value = path.display().to_string();
    if value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || matches!(ch, '/' | '.' | '_' | '-'))
    {
        value
    } else {
        format!("'{}'", value.replace('\'', "'\\''"))
    }
}
