//! Structure-fit skill files generated by `assura agent onboard`.

pub(super) fn skill() -> &'static str {
    r#"---
name: assura-structure-fit
description: Decide whether a structure mismatch should be fixed by moving/renaming a path or by updating Assura config.
applies_when: Handling Assura structure violations, new directories, or config-change proposals.
---

# Assura Structure Fit

Use this skill to apply `STRUCTURE_FIT_CHECK`: fix path shape first, update
config last.

## Workflow

1. Read the Assura finding and identify the rejected path.
2. Inspect existing repo shape before editing config.
3. Prefer reuse, move, or rename when the artifact fits an existing project
   role.
4. Propose a `.assura/config.yml` change only for a durable, non-duplicative
   role that matches project naming and structure.
5. Rerun `assura check --format agent --warn .` while drafting or
   `assura check --format json .` before handoff.

## Read as needed

| When | Read first |
| --- | --- |
| Handling a structure mismatch, new top-level directory, or config-change proposal | `references/structure-fit-check.md` |

## Outputs

- A path-first fix, or
- A concise config-change proposal with purpose, reuse analysis, naming pattern,
  allowed children, and validation command.

## Guardrails

- Do not treat structure violations as permission to loosen config.
- Do not use broad `allow_extra: true` or catch-all patterns without a project
  policy reason.
- Do not silently mutate host-agent/global skill config; keep this skill
  project-local under `.agents/skills/`.
"#
}

pub(super) fn reference() -> &'static str {
    r#"# STRUCTURE_FIT_CHECK

Use this reference when a new or moved path does not fit `.assura/config.yml`.

Short nudge:

```text
Structure mismatch: `{path}`. Apply STRUCTURE_FIT_CHECK before editing config.
```

Top-level path nudge:

```text
New top-level path: `{path}`. Apply STRUCTURE_FIT_CHECK with a 2-3 level repo map before editing config.
```

## Decision Frame

| Choice | Use when | Result |
| --- | --- | --- |
| Reuse existing home | The artifact fits an existing project role | Move or rename the path |
| Keep path, no config change | The path is temporary or should not be committed | Remove, ignore locally, or document as scratch |
| Update config | The path has a durable, distinct role | Add a narrow rule and validation proof |

## Config Change Bar

Only update `.assura/config.yml` after answering:

```text
Purpose:
Why existing paths do not fit:
Expected direct children:
Naming/style rule:
Related tests/docs/content records:
Validation command:
```

Prefer exact names, narrow patterns, `exists`, captures, `needs`, and
`provides` over broad extras. Keep config changes local to the smallest
directory scope that owns the policy.

## Onboarding Install

Assura onboarding installs this skill project-locally:

```text
.agents/skills/assura-structure-fit/SKILL.md
.agents/skills/assura-structure-fit/references/structure-fit-check.md
```

Generated guidance should route structure mismatches to the local skill or this
stable anchor. Assura preserves user-authored skill edits and does not silently
mutate host-agent or global skill configuration.
"#
}
