//! Static files generated by `assura agent onboard`.

use super::agent_onboarding::DetectedSection;
use super::agent_onboarding_content_templates as content;
use super::agent_onboarding_handoff_templates as handoff;
use super::agent_onboarding_structure_fit_templates as structure_fit;
use super::AgentContentTemplate;

pub(super) const AGENTIC_RECIPE: &str = "agentic-core + structure-health";
pub(super) const AGENT_ENTRYPOINT_REFERENCE: &str = "$agent-entrypoint";

pub(super) fn baseline_files(
    detected: &DetectedSection,
    content_template: AgentContentTemplate,
) -> Vec<GeneratedFile> {
    let mut files = vec![
        GeneratedFile {
            path: ".assura/config.yml",
            contents: agent_ready_config(content_template),
            required: true,
            executable: false,
        },
        GeneratedFile::static_file(".assura/presets.lock.yml", presets_lock()),
        GeneratedFile::static_file("AGENTS.md", agents_md()),
        GeneratedFile::static_file("README.md", project_readme()),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/SKILL.md",
            project_maintenance_skill(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/agents/openai.yaml",
            openai_agent_config(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-project-maintenance/references/assura-onboarding.md",
            onboarding_reference(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-structure-fit/SKILL.md",
            structure_fit::skill(),
        ),
        GeneratedFile::static_file(
            ".agents/skills/assura-structure-fit/references/structure-fit-check.md",
            structure_fit::reference(),
        ),
        GeneratedFile::static_file("docs/process/agent-workflow.md", agent_workflow_doc()),
        GeneratedFile::static_file("docs/learnings/README.md", learnings_readme()),
        GeneratedFile::static_file(
            ".assura/examples/agent-project/AGENTS.example.md",
            agents_example(),
        ),
        GeneratedFile::static_file(
            ".assura/examples/agent-project/SKILL.example.md",
            skill_example(),
        ),
        GeneratedFile {
            path: ".assura/onboarding/summary.md",
            contents: onboarding_summary(detected),
            required: true,
            executable: false,
        },
        GeneratedFile::static_file(".assura/onboarding/questions.md", handoff::questions()),
        GeneratedFile::static_file(".assura/onboarding/lifecycle.md", handoff::lifecycle()),
        GeneratedFile::static_file(".assura/onboarding/agent-next.md", handoff::agent_next()),
    ];
    files.extend(content::content_template_files(content_template));
    files
}

pub(super) fn rule_recommendations_file(detected: &DetectedSection, status: &str) -> GeneratedFile {
    GeneratedFile {
        path: ".assura/onboarding/rules.md",
        contents: onboarding_rules(detected, status),
        required: true,
        executable: false,
    }
}

#[derive(Clone)]
pub(super) struct GeneratedFile {
    pub(super) path: &'static str,
    pub(super) contents: String,
    pub(super) required: bool,
    pub(super) executable: bool,
}

impl GeneratedFile {
    pub(super) fn static_file(path: &'static str, contents: &'static str) -> Self {
        Self {
            path,
            contents: contents.to_string(),
            required: true,
            executable: false,
        }
    }
}

fn agent_ready_config(content_template: AgentContentTemplate) -> String {
    let repository_references = content::repository_reference_config(content_template);
    let requirements_traceability = content::requirements_traceability_config(content_template);
    let content_config = content::content_config(content_template);
    let root_structure = content::root_structure(content_template);
    let docs_structure = content::docs_structure(content_template);
    format!(
        r#"rules:
  # Progressive-disclosure entrypoints.
  agent-entrypoint:
    max_lines: 160
    severity: low
    message: See docs/process/agent-workflow.md.

  skill-entrypoint:
    max_lines: 500
    markdown:
      require_frontmatter: true
    message: See docs/process/agent-workflow.md#skills.

  # Shared non-blocking directory health.
  folder-health:
    limit_children: 10
    severity: low
    message: See docs/process/agent-workflow.md#structure.

  # Strict skill directories with declared resources.
  closed-entry:
    exists: 0
    message: See docs/process/agent-workflow.md#skills.

  closed:
    ./*/: $closed-entry
    ./*: $closed-entry

  skill:
    ./: $closed
    ./{{agents,assets,references,scripts}}/:
      ./: exists:0-1
      inherit: false
    SKILL.md: exists:1 | $skill-entrypoint

extensions:
  agent_guidance:
    - id: agent_project_guidance
      severity: low
      agents_path: AGENTS.md
      skill_paths:
        - ".agents/skills/*/SKILL.md"
      required_agents_sections:
        - Operating Rules
        - Process Docs vs Skills
        - Skills
        - Anchors
      required_skill_frontmatter:
        - name
        - description
        - applies_when
      required_skill_sections:
        - Workflow
        - Read as needed
        - Outputs
        - Guardrails
      skill_index_section: Skills
      best_practices_reference: "Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as concise indexes to deeper references."
      skill_routing_section: Skills
      allowed_skill_name_patterns:
        - "assura-*"
        - "assura_*"
      skill_reference_sections:
        - Read as needed
      skill_doc_routing_section: Read as needed
      skill_reference_prefixes:
        - references/
        - scripts/
        - assets/
        - docs/process/
        - .assura/onboarding/
      max_agents_lines: 160
      max_skill_lines: 120
{repository_references}
{requirements_traceability}
{content_config}

structure:
  # Agent entrypoints and project-owned skills.
  .agents/:
    ./: exists:0-1 | $closed
    skills/:
      ./: exists:0-1
      ./*/: kebab-case | $skill
      ./*: $closed-entry

  docs/:
    process/:
      agent-workflow.md: exists:1
    learnings/:
      README.md: exists:1
{docs_structure}
{root_structure}

  # Root files are explicit; project-specific manifests stay optional.
  .gitignore: exists:0-1
  AGENTS.md: exists:1 | $agent-entrypoint
  Cargo.toml: exists:0-1
  package.json: exists:0-1
  pyproject.toml: exists:0-1
  README.md: exists:1

  # Recursive advisory defaults.
  ./**/:
    ./: $folder-health
    .{{md,js,jsx,ts,tsx}}: max_lines:500 | severity:low

exclude:
  - ".assura/**"
  - ".git/**"
  - "target/**"
  - "node_modules/**"
  - "dist/**"
  - "**/dist/**"
"#
    )
}

fn presets_lock() -> &'static str {
    r#"schema: assura.presets-lock.v1
profile: agent-project
version: 1
generated_by: assura agent onboard
recipes:
  - agentic-core
  - structure-health
policy: project-owned
"#
}

fn project_readme() -> &'static str {
    "# Project\n\nProject guidance is in `AGENTS.md`.\n"
}

fn agents_md() -> &'static str {
    r#"# Agent Instructions

Assura has installed an agent-ready onboarding packet for this repository.
Read `.assura/onboarding/rules.md` for the project rule application status.

## Operating Rules

Before adding project-specific conventions, read
`.assura/onboarding/agent-next.md`. Use manifests, tooling, documentation, and
established paths as evidence for the expected project shape. Ask the user only
where that evidence is ambiguous or a rule would reject existing content.

Use `assura check --format agent --warn .` for advisory feedback while working.
Use gate-mode checks before push or CI by omitting `--warn`.

## Process Docs vs Skills

Use `docs/process/` for durable process documentation and use project-local
skills for repeatable agent workflows. Keep skill entrypoints concise.
Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as
concise indexes to deeper references.
Reference this best-practice message when editing agent guidance instead of
expanding AGENTS.md with long procedures.

## Skills

| When | Must first load |
| --- | --- |
| Maintaining the broad Assura baseline, onboarding packet, or specialization handoff | [`assura-project-maintenance`](.agents/skills/assura-project-maintenance/SKILL.md) |
| Handling an Assura structure mismatch or deciding whether config should allow a new path | [`assura-structure-fit`](.agents/skills/assura-structure-fit/SKILL.md) |

## Anchors

Use these section headings as stable anchors for agent routing:
Operating Rules, Process Docs vs Skills, Skills, Anchors.
"#
}

fn project_maintenance_skill() -> &'static str {
    r#"---
name: assura-project-maintenance
description: Maintain the project-local Assura baseline and onboarding packet.
applies_when: Maintaining the Assura baseline, onboarding packet, or specialization handoff.
---

# Assura Project Maintenance

## Workflow

Read `.assura/onboarding/agent-next.md` before specializing this repository.
Use `assura check --format agent --warn .` for advisory feedback while working.

## Read as needed

| When | Read first |
| --- | --- |
| Specializing the broad baseline | `references/assura-onboarding.md` |
| Choosing the next onboarding action | `.assura/onboarding/agent-next.md` |

## Outputs

- Updated Assura baseline files or a concise explanation that no baseline
  update was needed.
- Evidence-backed project-owned rules and clear remaining questions for the user.

## Guardrails

- Do not treat every observed path as intended. Close stable scopes from
  converging evidence and ask before making ambiguous or destructive choices.
- Keep longer examples and runbooks in `references/` or `docs/process/`.
"#
}

fn openai_agent_config() -> &'static str {
    "agent: openai\nprofile: assura-project-maintenance\n"
}

fn onboarding_reference() -> &'static str {
    "# Assura Onboarding\n\nRead `.assura/onboarding/rules.md`, inspect project evidence, specialize stable scopes, and ask only about unresolved choices.\n"
}

fn agent_workflow_doc() -> &'static str {
    r#"---
id: process-agent-workflow
title: Agent Workflow
status: active
related_requirements:
  - requirement-agent-content-baseline
---

# Agent Workflow

Run Assura checks, read agent-next.md, specialize from project evidence, and
ask only where the intended shape is ambiguous.
"#
}

fn learnings_readme() -> &'static str {
    r#"---
id: learning-agent-lessons
title: Agent Lessons
status: active
related_requirements:
  - requirement-agent-content-baseline
---

# Learnings

Record durable project lessons here when they affect future agent work.
"#
}

fn agents_example() -> &'static str {
    r#"# Agent Instructions Example

## Operating Rules

Replace with project-specific guidance after user answers.

## Process Docs vs Skills

Keep durable process docs in `docs/process/` and executable agent workflows in
project-local skills.
Progressive disclosure: keep AGENTS.md as a use-case router and SKILL.md as
concise indexes to deeper references.

## Skills

| When | Must first load |
| --- | --- |
| Running a repeatable project-local workflow | [`example-skill`](../../.agents/skills/example-skill/SKILL.md) |

## Anchors

Keep these headings stable for agent routing.
"#
}

fn skill_example() -> &'static str {
    r#"---
name: example-skill
description: Briefly describe the repeatable project-local workflow.
applies_when: Use when the project-local workflow is needed.
---

# Skill Example

## Workflow

Keep SKILL.md concise and put detailed references in subdirectories.

## Read as needed

| When | Read first |
| --- | --- |
| Running the workflow | `references/runbook.md` |

## Outputs

- Name the concrete artifact or status this skill should produce.

## Guardrails

- Move long examples into `references/` or `docs/process/`.
"#
}

fn onboarding_summary(detected: &DetectedSection) -> String {
    format!(
        "# Assura Onboarding Summary\n\nProject type: `{}` ({})\nAgent harness: `{}` ({})\nMaterialized recipes: `agentic-core`, `structure-health`\nPolicy ownership: `.assura/config.yml`\n\nSee `rules.md` for application status, then specialize the expected shape from project evidence.\n",
        detected.project_type,
        detected.project_confidence,
        detected.agent_harness,
        detected.agent_confidence
    )
}

fn onboarding_rules(detected: &DetectedSection, status: &str) -> String {
    let status_detail = match status {
        "applied" => "The project-owned agentic recipes are active.",
        "available" => {
            "Recipe rules are present, but the selected root policy does not apply all entrypoints."
        }
        "conflict" => "Existing project-owned recipe values were preserved and need manual review.",
        _ => "The selected config does not contain the recommended project-owned recipes.",
    };
    format!(
        "# Assura Rule Recommendations\n\nDetected project type: `{}`.\nRecommendation status: `{status}`.\n\n{status_detail}\n\nThe `agentic-core` and `structure-health` recipes are copied into `.assura/config.yml`; the project owns and can edit every selected rule.\n\nIncluded policy layers:\n\n- `$agent-entrypoint`\n- `$skill-entrypoint`\n- `$skill`\n- `$folder-health`\n- `$closed`\n\nUse project evidence to define language, framework, naming, layout, and generated-output rules. Ask the project owner only where the intended policy remains ambiguous.\n",
        detected.project_type,
    )
}
