//! Evidence-first handoff files generated by `assura agent onboard`.

pub(super) fn questions() -> &'static str {
    r#"# Unresolved Specialization Exceptions

Use repository evidence before asking the project owner anything. Record an
exception here only when instructions, manifests, tooling, and established
layout conflict or leave an essential policy decision unresolved.

For each exception, state the conflicting evidence, the decision that needs
human authority, and the policy surface it blocks. Do not use this file as a
generic setup questionnaire.
"#
}

pub(super) fn lifecycle() -> &'static str {
    r#"# Assura Lifecycle Profiles

Use these modes consistently:

| Mode | When | Blocking | Command |
| --- | --- | --- | --- |
| nudge | During agent working loops, path-aware tool events, and idle reviews | no | `assura agent nudge --event before-tool --changed <path> --format json .` |
| warn | Before local commits or while drafting | no | `assura check --format agent --warn --min-severity low --max-issues 10 .` |
| gate | Before push, merge, or CI | yes | `assura check --format agent --min-severity medium --max-issues 20 .` |

Host-agent integrations are reviewable local bundles under
`.assura/integrations/<agent>/`. Installation does not change host settings.
Run `assura agent integration activate <agent> .` to patch only Assura-owned
project host configuration, then `assura agent integration doctor <agent> .`
to verify the managed files. Host trust remains under user control.
"#
}

pub(super) fn agent_next() -> &'static str {
    r#"# Agent Next

Specialize from evidence; do not begin with a generic questionnaire.

1. Inspect explicit repository instructions, manifests, and established layout.
2. Preserve explicit local policy intent before selecting a pattern.
3. Select the smallest matching pattern from project evidence.
4. Record source, test, generated-output boundaries, and native tools.
5. Apply and validate the project-owned policy.
6. Configure integration and gate guidance.
7. Prove one negative policy case.
8. Report only unresolved exceptions.

Read `.assura/onboarding/rules.md` before editing `.assura/config.yml`. Use
`.assura/onboarding/lifecycle.md` for nudge, warn, and gate guidance. Apply
`STRUCTURE_FIT_CHECK` from
`.agents/skills/assura-structure-fit/references/structure-fit-check.md` before
changing policy for a structural mismatch.
"#
}
