//! Proposal/SBIR readiness scripts generated by the proposal domain pack.

pub(super) fn sh_readiness_script() -> &'static str {
    r#"#!/bin/sh
set -eu
findings=""

add_finding() {
  code="$1"
  path="$2"
  message="$3"
  item="{\"code\":\"$code\",\"path\":\"$path\",\"message\":\"$message\",\"severity\":\"high\"}"
  if [ -z "$findings" ]; then
    findings="$item"
  else
    findings="$findings,$item"
  fi
}

need_file() {
  path="$1"
  code="$2"
  message="$3"
  if [ ! -f "$path" ]; then
    add_finding "$code" "$path" "$message"
    return 1
  fi
  return 0
}

need_field() {
  path="$1"
  pattern="$2"
  code="$3"
  message="$4"
  if ! grep -Eq "$pattern" "$path"; then
    add_finding "$code" "$path" "$message"
  fi
}

scorecard="proposals/scorecards/scorecard-sbir-baseline.md"
if need_file "$scorecard" "missing_scorecard" "Proposal SBIR scorecard is missing"; then
  need_field "$scorecard" "^status: ready$" "scorecard_not_ready" "Proposal SBIR scorecard status must be ready"
  need_field "$scorecard" "^weighted_score: [1-9][0-9]*$" "score_missing_weighted_score" "Proposal SBIR scorecard must include a positive weighted_score"
  need_field "$scorecard" "^threshold_score: [1-9][0-9]*$" "score_missing_threshold" "Proposal SBIR scorecard must include a positive threshold_score"
fi
review="proposals/review-findings/finding-sbir-technical-review.md"
if need_file "$review" "missing_review_finding" "Proposal SBIR technical review finding is missing"; then
  need_field "$review" "^status: resolved$" "review_not_resolved" "Proposal SBIR review finding must be resolved before package readiness"
  need_field "$review" "^owner: .+$" "review_missing_owner" "Proposal SBIR review finding must carry owner metadata"
fi
package="proposals/package/package-manifest-sbir-baseline.md"
if need_file "$package" "missing_package_manifest" "Proposal SBIR package manifest is missing"; then
  need_field "$package" "^status: ready$" "package_not_ready" "Proposal SBIR package manifest status must be ready"
  need_field "$package" "^final_package_path: docs/final/final-document-project-baseline.md$" "package_missing_final_path" "Proposal SBIR package manifest must point at the final package path"
fi
checklist="proposals/submission/submission-checklist-sbir-baseline.md"
if need_file "$checklist" "missing_submission_checklist" "Proposal SBIR submission checklist is missing"; then
  need_field "$checklist" "^status: ready$" "submission_not_ready" "Proposal SBIR submission checklist status must be ready"
fi
printf '{"schema":"assura.computed-check.output.v1","findings":[%s]}\n' "$findings"
"#
}

pub(super) fn cmd_readiness_script() -> &'static str {
    r#"@echo off
setlocal EnableExtensions EnableDelayedExpansion
set "findings="

call :need_file "proposals\scorecards\scorecard-sbir-baseline.md" "proposals/scorecards/scorecard-sbir-baseline.md" "missing_scorecard" "Proposal SBIR scorecard is missing"
if not errorlevel 1 (
  call :need_field "proposals\scorecards\scorecard-sbir-baseline.md" "status: ready" "scorecard_not_ready" "Proposal SBIR scorecard status must be ready" "proposals/scorecards/scorecard-sbir-baseline.md"
  call :need_field "proposals\scorecards\scorecard-sbir-baseline.md" "weighted_score:" "score_missing_weighted_score" "Proposal SBIR scorecard must include weighted_score" "proposals/scorecards/scorecard-sbir-baseline.md"
  call :need_field "proposals\scorecards\scorecard-sbir-baseline.md" "threshold_score:" "score_missing_threshold" "Proposal SBIR scorecard must include threshold_score" "proposals/scorecards/scorecard-sbir-baseline.md"
)
call :need_file "proposals\review-findings\finding-sbir-technical-review.md" "proposals/review-findings/finding-sbir-technical-review.md" "missing_review_finding" "Proposal SBIR technical review finding is missing"
if not errorlevel 1 (
  call :need_field "proposals\review-findings\finding-sbir-technical-review.md" "status: resolved" "review_not_resolved" "Proposal SBIR review finding must be resolved before package readiness" "proposals/review-findings/finding-sbir-technical-review.md"
  call :need_field "proposals\review-findings\finding-sbir-technical-review.md" "owner:" "review_missing_owner" "Proposal SBIR review finding must carry owner metadata" "proposals/review-findings/finding-sbir-technical-review.md"
)
call :need_file "proposals\package\package-manifest-sbir-baseline.md" "proposals/package/package-manifest-sbir-baseline.md" "missing_package_manifest" "Proposal SBIR package manifest is missing"
if not errorlevel 1 (
  call :need_field "proposals\package\package-manifest-sbir-baseline.md" "status: ready" "package_not_ready" "Proposal SBIR package manifest status must be ready" "proposals/package/package-manifest-sbir-baseline.md"
  call :need_field "proposals\package\package-manifest-sbir-baseline.md" "final_package_path: docs/final/final-document-project-baseline.md" "package_missing_final_path" "Proposal SBIR package manifest must point at the final package path" "proposals/package/package-manifest-sbir-baseline.md"
)
call :need_file "proposals\submission\submission-checklist-sbir-baseline.md" "proposals/submission/submission-checklist-sbir-baseline.md" "missing_submission_checklist" "Proposal SBIR submission checklist is missing"
if not errorlevel 1 (
  call :need_field "proposals\submission\submission-checklist-sbir-baseline.md" "status: ready" "submission_not_ready" "Proposal SBIR submission checklist status must be ready" "proposals/submission/submission-checklist-sbir-baseline.md"
)
echo {"schema":"assura.computed-check.output.v1","findings":[!findings!]}
exit /b 0

:need_file
if not exist "%~1" (
  call :add_finding "%~3" "%~2" "%~4"
  exit /b 1
)
exit /b 0

:need_field
findstr /C:"%~2" "%~1" >nul
if errorlevel 1 call :add_finding "%~3" "%~5" "%~4"
exit /b 0

:add_finding
set "item={^"code^":^"%~1^",^"path^":^"%~2^",^"message^":^"%~3^",^"severity^":^"high^"}"
if "!findings!"=="" (
  set "findings=!item!"
) else (
  set "findings=!findings!,!item!"
)
exit /b 0
"#
}
